from epstein_files.documents.documents.categories import Interesting, Neutral, Uninteresting
from epstein_files.documents.doj_files.full_text import EFTA00009622_TEXT
from epstein_files.documents.config.communication_cfg import (CommunicationCfg, TextCfg, imessage_log,
     imessage_screenshot, skype_log, whatsapp_log)
from epstein_files.documents.config.config_builder import letter
from epstein_files.documents.config.doc_cfg import NO_TRUNCATE, DocCfg
from epstein_files.documents.config.email_cfg import SNEAKY_DOG, EmailCfg
from epstein_files.documents.config.pic_cfg import PicCfg
from epstein_files.people.names import *
from epstein_files.util.constant.strings import *
from epstein_files.util.constant.urls import DITE_ANATA_JUILLIARD_URL, JULIA_SANTOS_REDDIT_URL, PRUSAKOVA_REDDIT_URL, SVETLANA_NEWSGROUND
from epstein_files.util.helpers.string_helper import join_truthy, quote
from epstein_files.util.logging import logger

PRUSAKOVA_BERKELY = 'Epstein paid for Prusakova to go to Berkeley'
WOMEN_EMPOWERMENT = f"{WOMAN_EMPOWERMENT} (WE) conference"


def immigration_letter(id: str, author: Name, date: str = '', note: str = '', show_with_name = '', **kwargs) -> CommunicationCfg:
    """`show_with_name` is who the letter is about."""
    person_recommended_for_visa = show_with_name or 'someone'
    suffix = f"recommending \"genius\" visa for {person_recommended_for_visa}"

    if person_recommended_for_visa not in note:
        note = join_truthy(note, suffix)

    return letter(
        id,
        author=author,
        date=date,
        is_interesting=10,
        note=note,
        recipients=['INS'],
        show_with_name=show_with_name,
        **kwargs
    )


def blaine_letter(id: str, date: str, suffix: str = '', **kwargs) -> CommunicationCfg:
    return immigration_letter(
        id,
        DAVID_BLAINE,
        date=date,
        note=join_truthy(f"recommending genius visa for a Epstein's assistant {SVETLANA_POZHIDAEVA}", suffix),
        show_with_name=SVETLANA_POZHIDAEVA,
        **kwargs
    )


GIRLS_CFGS = [
    DocCfg(
        id='019300',
        author=SVETLANA_POZHIDAEVA,
        date='2019-04-05',
        duplicate_ids=['EFTA00810724'],
        note=f'{WOMEN_EMPOWERMENT} f. {KATHRYN_RUEMMLER}',
        show_full_panel=True,
        show_with_name=KATHRYN_RUEMMLER,
    ),
    DocCfg(id='022267', author=SVETLANA_POZHIDAEVA, note=f'{WOMEN_EMPOWERMENT} founder essay about growing the seminar business'),
    DocCfg(id='022407', author=SVETLANA_POZHIDAEVA, note=f'{WOMEN_EMPOWERMENT} seminar pitch deck'),
    EmailCfg(id='031177', highlight_quote="in Ibiza so invited a lots of girls from Russia all models"),
    EmailCfg(id='030152', note=f"model scout Tigrane apparently used to work for Trump Models"),
    EmailCfg(id='025874', note=f"possibly about {VIRGINIA_GIUFFRE} {QUESTION_MARKS}"),
    EmailCfg(id='030609', duplicate_ids=['030495']),
    EmailCfg(id='026998', note=f"{JONATHAN_FARKAS} in love with an Epstein girl"),
    EmailCfg(id='EFTA00540166', note=f"irregular admission of {KARYNA_SHULIAK} to Columbia Dental School", truncate_to=2_000),
    EmailCfg(id='EFTA00539168', note=f"irregular admission of {KARYNA_SHULIAK} to Columbia Dental School"),
    EmailCfg(id='EFTA00535421', note=f"irregular admission of {KARYNA_SHULIAK} to Columbia Dental School"),
    EmailCfg(id='EFTA00683288', note=f"irregular admission of {KARYNA_SHULIAK} to Columbia Dental School", truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA00529914', note=f"special help from Columbia Dental School for {KARYNA_SHULIAK}"),

    # DOJ Files
    DocCfg(
        id='EFTA01297974',
        note=f"DOJ queries OffshoreLeaks database for {SVETLANA_POZHIDAEVA}'s mother",
        show_full_panel=True,
        show_with_name=SVETLANA_POZHIDAEVA,
        truncate_to=500,
    ),
    DocCfg(id='EFTA02701609', author=GIANNI_SERAZZI, note='2morrow business plan', date='2014-09-30', date_uncertain=True),
    DocCfg(id='EFTA01078143', author=GIANNI_SERAZZI, note='2morrow modeling pitch deck', date='2014-09-30', date_uncertain=True),
    DocCfg(id='EFTA00306033', author=SERGEY_BELYAKOV, note='Epstein Russian visa', show_full_panel=True),  # TODO: this belong here?
    DocCfg(
        id='EFTA01366289',
        author=BUTTERFLY_TRUST,
        date='2015-03-30',
        is_interesting=20,
        note=f"transfer of $237,270 to {SVETLANA_POZHIDAEVA}'s father's Raiffeisenbank from account at Standard Chartered Bank",
        show_full_panel=True,
        show_with_name=SVETLANA_POZHIDAEVA,
    ),
    DocCfg(id='EFTA00014648', note='former employee "understood that all the girls were school girls"', show_full_panel=True),
    DocCfg(id='EFTA00022133', note='table listing Epstein accusations collated from the press and court hearings'),
    DocCfg(
        id='EFTA00077200',
        author=FRENCH_MINISTRY_OF_JUSTICE,
        date='2020-07-08',
        note=f'allegations that {JEAN_LUC_BRUNEL} drugged a model and Epstein + Ghislaine assaulted a minor',
    ),
    DocCfg(
        id='EFTA00079597',
        author=FRENCH_MINISTRY_OF_JUSTICE,
        note=f"allegations of sexual assault by {JEAN_LUC_BRUNEL}",
        date='2020-07-08',
    ),
    DocCfg(
        id='EFTA01114895',
        author=MARIA_PRUSAKOVA,
        date='2016-06-01',
        date_uncertain='near her move to Berkley',
        note='application letter to UC Berkeley',
    ),
    DocCfg(
        id='EFTA00276977',
        date='2021-07-21',
        highlight_quote="I have fear around her (Gm) Gm is extremely dangerous person behavior I’ve seen sociopathic",
        note='notes from Emma Sergeant interview describing being introduced to Trump by Epstein & Maxwell',
        truncate_to=(6_400, 7_800),
    ),
    DocCfg(
        id='EFTA00143433',
        date='2022-06-01',
        date_uncertain='approx based on JPM lawsuit Nov 22',
        note='victim impact statement',
    ),

    # Communications
    CommunicationCfg(
        id='EFTA01612665',
        note='Epstein gives advice on how to recruit girls',
        highlight_quote="stressed about finding girls. It's hard",
        is_interesting=5,
        show_full_panel=True,
        truncate_to=AUTO,
    ),
    imessage_log(
        id='EFTA02731576',
        is_interesting=10,
        note=f"making contemporaneous accusations",
        recipients=[LEON_BLACK],
        show_full_panel=True,
    ),
    imessage_log('EFTA01616775', author=BECHET_ALLEN, date='2017-03-29', note=f"grooming {BECHET_ALLEN}"),
    imessage_log(id='EFTA01617521', author=EDUARDO_TEODORANI),
    imessage_screenshot(
        'EFTA01619579',
        author=DEEPAK_CHOPRA,
        is_in_chrono=False,
        truncate_to=500,
    ),
    imessage_screenshot(
        'EFTA01617527',
        author=EDUARDO_TEODORANI,
        highlight_quote='interesting pussy than Fl in Milano interesting pussy as well',
        is_interesting=True,
        truncate_to=(1_700, 2_200),
    ),
    imessage_screenshot(
        'EFTA01618381',
        author=RENATA_BOLOTOVA,
        author_uncertain='sneaky',
        highlight_quote='how many new girls are there in the island W you now?',
        truncate_to=(1_774, 3_000),
    ),
    imessage_screenshot('EFTA02731525', author=LEON_BLACK, author_uncertain=True, is_interesting=10),
    imessage_screenshot('EFTA01622387', author=RENATA_BOLOTOVA, author_uncertain='sneaky'),
    imessage_screenshot('EFTA01618494', author=RENATA_BOLOTOVA, author_uncertain='sneaky'),
    imessage_screenshot('EFTA01618400', author=RENATA_BOLOTOVA, author_uncertain='sneaky'),
    letter('EFTA00078198', 'Marsh Law Firm', [USANYS], "allegations of sexual abuse at Epstein's house", '2020-11-10'),
    skype_log(
        id='EFTA01616933',
        date='2019-04-08',
        note='"no one can beat your pussy network"',
        highlight_quote='now im finding pussy for you',
        truncate_to=AUTO,
    ),
    skype_log(
        id='EFTA01623342',
        author=ANNA_KASATKINA,
        author_uncertain=True,
        highlight_quote='send me your bank account details . i will send you the money for your life in moscow',
        is_interesting=15,
        note=f'Epstein paying {ANNA_KASATKINA} or {JULIA_SANTOS} to recruit Russian girls',
        truncate_to=AUTO,
        url=JULIA_SANTOS_REDDIT_URL,
    ),
    skype_log(
        id='EFTA01613468',
        author=EKATERINA_GUSAROVA,
        author_uncertain='Carstensen',
    ),
    skype_log('EFTA01621978', author=DANIEL_SIAD, date='2017-04-04'),
    skype_log('EFTA01612650', author=MASHA_DROKOVA, date='2019-05-15'),
    skype_log(
        'EFTA01612695',
        author=DANIEL_SIAD,
        date='2019-02-05',
        highlight_quote="my friend the Thai actrice is new York if you have time to invite her",
        is_interesting=True,
        truncate_to=(300, 450),
    ),
    whatsapp_log(
        id='EFTA01612733',
        author=MARIA_PRUSAKOVA,
        author_uncertain=True,
        date='2019-05-08',
        highlight_quote='way better than supplying you ladies',
        note=f'saying being Epstein\'s lawyer would be preferable to recruiting, discusses Medici Bank',
        truncate_to=AUTO,
    ),

    # Authors
    EmailCfg(
        id='EFTA01742539',
        author=EKATERINA_GUSAROVA,
        author_reason='Carstensen',
        highlight_quote='tell katya that you will pay her for recommendations that work out',
    ),
    EmailCfg(
        id='EFTA00383531',
        author='Frederika Finkelstein',
        note=f"Epstein attempting to recruit Frederika Finkelstein",
        is_in_chrono=False,
    ),
    EmailCfg(
        id='EFTA02339926',
        author=JULIA_SANTOS,
        author_uncertain=JULIA_SANTOS_REDDIT_URL,
        highlight_quote='very sweet and might be naughty t=o',
    ),
    EmailCfg(id='EFTA00448706', show_with_name=JULIA_SANTOS),
    EmailCfg(
        id='EFTA01745650',
        author=KIRA_DIKHTYAR,
        author_uncertain='AOL signature',
        is_interesting=20,
        note=f'{SANITA} is big mad at Epstein and "makes lists" which is freaking everyone out',
        show_with_name=SANITA,
        truncate_to=NO_TRUNCATE,
    ),
    EmailCfg(id='EFTA00830533', author=KIRA_DIKHTYAR, author_uncertain='Carstensen', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA01781620', author=KIRA_DIKHTYAR, author_uncertain='"Sent from AOL Mobile Mail" in chain'),
    EmailCfg(id='EFTA01805304', author=KIRA_DIKHTYAR, author_reason='Jmail', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA01766199', author=KIRA_DIKHTYAR, author_reason='reply', truncate_to=NO_TRUNCATE),
    EmailCfg(
        id='EFTA00643691',
        is_interesting=12,
        note=f"{KIRA_DIKHTYAR} connecting {NATALIA_SHAVKUNOVA} and asking for Warren Buffett's autograph for Mikhail Prokhorov",
    ),
    EmailCfg(id='EFTA00464793', author=LESLEY_GROFF, note=f"{EVA_DUBIN} possibly providing drugs on request"),
    EmailCfg(id='EFTA00685910', author=SANITA, author_reason="signature in replies"),
    EmailCfg(id='EFTA01890941', highlight_quote=f"{LOLA_MIGNON} announces her pseudonym", is_interesting=5),
    EmailCfg(id='EFTA01759826', highlight_quote='especially if you find me interesing girls there', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA01969878', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA01981669', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA00876896', author=LAURA_T_NEWMAN, author_reason='visible in quoted'),
    EmailCfg(id='EFTA00737310', author=LAURA_T_NEWMAN, author_uncertain='". xo"'),
    EmailCfg(id='EFTA01791918', author=LAURA_T_NEWMAN, note='recruiting a ballet dancer', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA02436739', author=LAURA_T_NEWMAN, note='recruiting?'),
    EmailCfg(
        id='033178',
        author=MARIA_PRUSAKOVA,
        author_reason=PRUSAKOVA_BERKELY,
        is_interesting=20,
        note=f'Masha Prusso asks about {ZUBAIR_KHAN}, discusses recruiting girls for Epstein',
    ),
    EmailCfg(
        id='EFTA00669538',
        author=MARIA_PRUSAKOVA,
        author_uncertain='discussion of "experiments"',
        note='blowjob instructions, sexual experiments',
        truncate_to=NO_TRUNCATE,
    ),
    EmailCfg(
        id='EFTA02010589',
        author=MARIA_PRUSAKOVA,
        date='2012-01-31 9:16 PM',
        highlight_quote='your job is to find interesting girls',
        note=f'note {BORIS_NIKOLIC} and bgC3 (Gates Foundation) in SMTP info at end',
        recipients=[JEFFREY_EPSTEIN],
    ),
    EmailCfg(
        id='EFTA00928879',
        author=MARIA_PRUSAKOVA,
        author_uncertain='sounds like her',
        duplicate_ids=['EFTA01840887'],
        dupe_type='quoted',
        note=f'raunchy email',
        truncate_to=1_000,
    ),
    EmailCfg(
        id='EFTA01841553',
        author=MARIA_PRUSAKOVA,
        author_uncertain=True,
        highlight_quote='being fucked in the ass hurts me a lot',
        truncate_to=900,
    ),
    EmailCfg(
        id='032374',
        author=MARIA_PRUSAKOVA,
        author_reason=PRUSAKOVA_BERKELY,
        note='boyfriend named Christian mentioned',
    ),
    EmailCfg(
        id='EFTA02351139',
        author=MARIA_PRUSAKOVA,
        author_uncertain=PRUSAKOVA_BERKELY,
        highlight_quote='ok, no more over 24! Sorry for that.',
        truncate_to=3_200,
    ),
    EmailCfg(
        id='EFTA02030653',
        author=MARIA_PRUSAKOVA,
        author_uncertain=PRUSAKOVA_REDDIT_URL,
        highlight_quote='you are interested in me only because I found pretty girls for you?',
        truncate_to=AUTO,
    ),
    EmailCfg(
        id='EFTA01844887',
        author=MARIA_PRUSAKOVA,
        author_uncertain=PRUSAKOVA_REDDIT_URL,
        highlight_quote="to work as escort girl, to go for dinners, be someone's company and maybe have sex for the agency",
        truncate_to=AUTO,
    ),
    EmailCfg(
        id='EFTA01993032',
        is_interesting=9,
        note=f'{IAN_OSBORNE} calls Greg Craig "my guy", offers to help with visa for woman Epstein "prefers not be part of my file"',
    ),
    EmailCfg(id='032375', author=MARIA_PRUSAKOVA, author_reason=PRUSAKOVA_BERKELY, truncate_to=295),
    EmailCfg(id='033246', author=MARIA_PRUSAKOVA, author_reason='Kind regards/Cordialement in signature'),
    EmailCfg(id='EFTA00920848', author=MARIA_PRUSAKOVA, author_uncertain='law school'),
    EmailCfg(id='EFTA02038002', author=MARIA_PRUSAKOVA, author_uncertain=CLIFFORD_CHANCE, highlight_quote="did you find the my new girlfrined?"),
    EmailCfg(id='EFTA02036490', author=MARIA_PRUSAKOVA, author_uncertain=CLIFFORD_CHANCE),
    EmailCfg(id='EFTA02022813', author=MARIA_PRUSAKOVA, author_uncertain=CLIFFORD_CHANCE, highlight_quote='I want to learn more sexual tricks'),
    EmailCfg(id='EFTA02001536', author=MARIA_PRUSAKOVA, author_uncertain=CLIFFORD_CHANCE),
    EmailCfg(id='EFTA01772533', author=MARIA_PRUSAKOVA, author_uncertain=CLIFFORD_CHANCE),
    EmailCfg(id='EFTA01775280', author=MARIA_PRUSAKOVA, author_uncertain=CLIFFORD_CHANCE, truncate_to=2000),
    EmailCfg(id='EFTA02507271', author=MARIA_PRUSAKOVA, author_uncertain='LGT Bank in signature'),
    EmailCfg(id='EFTA01990168', author=MARIA_PRUSAKOVA, author_uncertain='"experiments"'),
    EmailCfg(id='EFTA02026255', author=MARIA_PRUSAKOVA, author_uncertain=CLIFFORD_CHANCE, truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA00684871', author=MARIANA_IDZKOWSKA),
    EmailCfg(id='EFTA00674483', author=MARIANA_IDZKOWSKA),
    EmailCfg(
        id='EFTA00662373',
        author=MASHA_DROKOVA,
        author_reason='"Best, Masha"',
        highlight_quote='She is interesting. Great looks',
        is_interesting=True,
    ),
    EmailCfg(id='EFTA02221224', note=f"buying a Prada handbag for {MASHA_DROKOVA}", show_with_name=MASHA_DROKOVA),
    EmailCfg(id='EFTA01990879', author=MIRANDA_MAKO, author_uncertain='Clifford Chance, could be Miranda'),
    EmailCfg(id='EFTA00671662', author=MIRANDA_MAKO, author_reason='quoted signature "Miranda"', note="yet another girl finder"),

    # Alysia
    EmailCfg(id='EFTA01154417', recipients=[ALYSIA_RIABENKOVA], recipient_uncertain=True),

    # Nadia
    EmailCfg(id='021814', author=NADIA_MARCINKO, author_reason='reply'),
    EmailCfg(id='021808', author=NADIA_MARCINKO, author_reason='reply', truncate_to=NO_TRUNCATE),
    EmailCfg(id='021818', author=NADIA_MARCINKO, author_reason='reply'),
    EmailCfg(id='022214', author=NADIA_MARCINKO, author_reason='Reply header'),
    EmailCfg(id='021811', author=NADIA_MARCINKO, author_reason='signature and email address in the message'),
    EmailCfg(
        id='EFTA01015310',
        author_reason='thank you Nadia',
        highlight_quote="wire was sent today from JEGE LLC to Aviloop account",
        recipients=[NADIA_MARCINKO],
    ),
    EmailCfg(id='EFTA00877202', recipients=[NADIA_MARCINKO], recipient_uncertain='"Aviloop"'),
    EmailCfg(id='EFTA00966975', recipients=[NADIA_MARCINKO], recipient_uncertain='"Aviloop"'),
    EmailCfg(id='EFTA00966504', recipients=[NADIA_MARCINKO], recipient_uncertain='"Aviloop"'),
    EmailCfg(
        id='EFTA01015397',
        author=NADIA_MARCINKO,
        author_uncertain='"Aviloop"',
        is_interesting=4,
        note=f"routing money through {NADIA_MARCINKO}'s Aviloop LLC, possibly to show income for visa/immigration purposes",
    ),
    EmailCfg(id='EFTA01047249', author=NADIA_MARCINKO, author_reason='Miro', url='https://archive.ph/Qa6vU#selection-1621.160-1621.184'),
    EmailCfg(
        id='EFTA00962525',
        author=NADIA_MARCINKO,
        author_reason='carstensen',
        highlight_quote="I was a teenager in love. You were 51.",
        is_interesting=2,
    ),
    EmailCfg(id='EFTA01897098', author=NADIA_MARCINKO, note=f"{NADIA_MARCINKO} wants $5 million to part with Epstein"),
    EmailCfg(id='EFTA00677154', author=NADIA_MARCINKO),
    EmailCfg(
        id='EFTA02456758',
        note=f'financial support for {NADIA_MARCINKO} or Nadia Bjorlin',
        recipients=[NADIA_MARCINKO, RICHARD_KAHN],
        recipient_uncertain='could be Bjorlin',
        show_with_name=NADIA_MARCINKO,
    ),
    EmailCfg(id='EFTA00737722', recipients=[NADIA_MARCINKO], author_reason='visible in quoted replies'),
    EmailCfg(
        id='EFTA00876637',
        is_interesting=5,
        note=f"accounting of money spent on or given to {NADIA_MARCINKO}",
        show_with_name=NADIA_MARCINKO,
    ),

    # Natalya Malyshev
    EmailCfg(id='EFTA00752360', recipients=[JEFFREY_EPSTEIN]),

    # Naya
    DocCfg(id='EFTA00303504', note=f'travel arrangements for {NATALIA_SHAVKUNOVA}', date='2016-02-14', truncate_to=600),

    # Renata
    EmailCfg(
        id='EFTA00429257',
        author=POLINA_BELOMLINSKAYA,
        author_uncertain=True,
        recipients=[BELLA_KLEIN],
        recipient_uncertain=True,
    ),
    EmailCfg(
        id='EFTA02538649',
        author=RENATA_BOLOTOVA,
        author_reason=f'{SNEAKY_DOG} + {TERJE_ROD_LARSEN} mention',
        note=f"email about a future job at {TERJE_ROD_LARSEN}'s International Peace Institute",
    ),
    EmailCfg(
        id='EFTA02540487',
        author=RENATA_BOLOTOVA,
        author_reason=f'{SNEAKY_DOG} + {TERJE_ROD_LARSEN} mention',
        is_interesting=10,
        note=f"email about a job for {RENATA_BOLOTOVA} at {TERJE_ROD_LARSEN}'s International Peace Institute",
    ),
    EmailCfg(id='EFTA00775732', author='Sarah', author_reason='https://jmail.world/thread/EFTA02443569?view=inbox'),
    EmailCfg(id='EFTA02441035', author=STEVEN_VICTOR_MD, note="complaints about free medical treatment for Epstein's girls"),

    # Sue
    EmailCfg(id='EFTA00664619', author=SUE, author_reason='"Dear Sue"'),

    # Svetlana
    EmailCfg(
        id='EFTA00659941',
        author=SVETLANA_POZHIDAEVA,
        author_reason='https://tommycarstensen.com/epstein/findings.html#victim-diary-names-multiple-men',
        is_interesting=12,
        note=f'{SVETLANA_POZHIDAEVA} forwarding her intimate conversations with {JOSHUA_FINK} to Epstein (to what end?)',
    ),
    EmailCfg(
        id='EFTA01844498',
        author=SVETLANA_POZHIDAEVA,
        author_reason='Josh Fink, BlackBerry signature',
        is_interesting=12,
        note=f"jealous boyfriend {JOSHUA_FINK} accuses Svetlana of having an affair with Navalny {QUESTION_MARKS}",
    ),
    EmailCfg(
        id='EFTA01870453',
        author=SVETLANA_POZHIDAEVA,
        author_uncertain=f"{JOSHUA_FINK} texts",
        highlight_quote="You have known you are preg for a week",
        note=f'{SVETLANA_POZHIDAEVA} fwds intimate texts from Joshua Fink about an abortion to Epstein',
    ),
    EmailCfg(id='EFTA02449228', recipients=[SVETLANA_POZHIDAEVA], recipient_uncertain='Carstensen'),
    EmailCfg(id='EFTA02439200', author=SVETLANA_POZHIDAEVA, duplicate_ids=['EFTA02439624'], dupe_type='quoted'),
    DocCfg(id='EFTA02445716', author=SVETLANA_POZHIDAEVA, note=f'{WOMEN_EMPOWERMENT} pilot event', date='2019-04-12'),
    EmailCfg(
        id='EFTA01894879',
        note='"most of all its cheap excort"',
        duplicate_ids=['EFTA00876711'],
        highlight_quote='400 girls for model agencies and wedding agencies',
        recipients=[SVETLANA_POZHIDAEVA],
        recipient_uncertain='"Svet"',
    ),
    EmailCfg(
        id='EFTA01991293',
        author=SVETLANA_POZHIDAEVA,
        author_reason=f"convo about {JOSHUA_FINK} breakup",
        is_interesting=20,
        note=f'did {ELON_MUSK} date {SVETLANA_POZHIDAEVA} after she blackmailed {JOSHUA_FINK}? ("he asked 6 times if Elon [gave] me anything")',
    ),
    EmailCfg(
        id='EFTA01998247',
        author=SVETLANA_POZHIDAEVA,
        author_uncertain='device signature',
        note=f'trying to recruit {ELON_MUSK}?',
        is_interesting=20,
        show_with_name=ELON_MUSK,
    ),
    EmailCfg(
        id='EFTA01894132',
        author=SVETLANA_POZHIDAEVA,
        author_uncertain='"Svet" in unredacted reply',
        truncate_to=(900, 1_600),
    ),
    EmailCfg(
        id='EFTA01926961',
        author=SVETLANA_POZHIDAEVA,
        highlight_quote="If you take too many more trips to Russia, I'm going to assume that you're FSB/ KGB by your parents",
    ),
    EmailCfg(id='EFTA00846558', note=f"{SVETLANA_POZHIDAEVA} meets {MASHA_DROKOVA}", truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA01877224', author=SVETLANA_POZHIDAEVA, author_reason=f"{JOSHUA_FINK} texts", is_interesting=20, note=f"intimate texts with {JOSHUA_FINK}"),
    EmailCfg(id='EFTA00937507', author=SVETLANA_POZHIDAEVA, author_reason=f"{JOSHUA_FINK} texts", is_interesting=20, note=f"intimate texts with {JOSHUA_FINK}"),
    EmailCfg(id='EFTA01805014', author=SVETLANA_POZHIDAEVA, author_uncertain='"BlackBerry from T-Mobile"', note=f'recruiting "Regina"'),
    EmailCfg(id='EFTA01772677', author=SVETLANA_POZHIDAEVA, author_uncertain='device signature'),
    EmailCfg(id='EFTA02605514', author=SVETLANA_POZHIDAEVA, note=f"{SVETLANA_POZHIDAEVA} meets {BILL_GATES}"),
    EmailCfg(id='EFTA02634573', author=SVETLANA_POZHIDAEVA, note='updating Epstein on Women Empowerment'),
    EmailCfg(id='EFTA01024246', is_interesting=10, note=f"invoice from {SVETLANA_POZHIDAEVA}'s WE Talks", show_with_name=SVETLANA_POZHIDAEVA),
    EmailCfg(
        id='EFTA01744405',
        author=SVETLANA_POZHIDAEVA,
        is_interesting=10,
        note=f"{SVETLANA_POZHIDAEVA} discusses her father (an FSB officer) and 'Josh' (presumably {JOSHUA_FINK})",
        url=SVETLANA_NEWSGROUND,
    ),
    EmailCfg(
        id='EFTA02475964',
        note=f"Epstein thanks {SVETLANA_POZHIDAEVA}'s father, a former (?) FSB officer",
        is_interesting=20,
        recipients=[SVETLANA_POZHIDAEVA],
        url=SVETLANA_NEWSGROUND,
    ),
    EmailCfg(
        id='EFTA02439624',
        author_reason='cyrillic',
        is_interesting=4,
        note=f"{SVETLANA_POZHIDAEVA} showering Jeffrey with affection",
        recipients=[SVETLANA_POZHIDAEVA],
    ),
    EmailCfg(
        id='EFTA02480401',
        highlight_quote='i re=iewed payment of 237,270 for svet family',
        is_interesting=20,
        note=f'"svet family" is {SVETLANA_POZHIDAEVA}\'s family in Russia',
        show_with_name=SVETLANA_POZHIDAEVA,
    ),
    EmailCfg(id='EFTA00679975', author=UNKNOWN_GIRL),
    EmailCfg(id='EFTA02431535', author=UNKNOWN_GIRL),
    EmailCfg(id='EFTA01875607', author=UNKNOWN_GIRL),
    EmailCfg(id='EFTA01789837', author=UNKNOWN_GIRL),
    EmailCfg(id='EFTA00901581', author=UNKNOWN_GIRL, highlight_quote='he got crazy, punched her in front of all the friends', is_interesting=True),
    EmailCfg(id='EFTA02416005', author=UNKNOWN_GIRL, highlight_quote="he'll put me in touch with a romanian lady wich knows everything in London", is_interesting=True),
    EmailCfg(id='EFTA02565917', author=UNKNOWN_GIRL, note='Hassan Mohammed Abdul Latif Jameel is a Saudi businessman and philanthropist'),
    EmailCfg(id='EFTA02449477', author=UNKNOWN_GIRL, note='argument about finding girls for Epstein', is_interesting=10, truncate_to=NO_TRUNCATE),
    EmailCfg(
        id='EFTA00686588',
        author=MARIA_PRUSAKOVA,
        author_uncertain='"agreement_M+J.DOC" attachment name',
        highlight_quote="The Apprentice will find beautiful women among her friends and acquaintances",
        note='contract for recruitment and sexual favours',
        truncate_to=3_700,
    ),
    EmailCfg(
        id='EFTA02027844',
        author=UNKNOWN_GIRL,
        highlight_quote='fuck someone with a condom',
        note='asking permission to',
        truncate_to=NO_TRUNCATE,
    ),
    EmailCfg(id='EFTA00763537', author=UNKNOWN_GIRL, highlight_quote="19 but I look younger than her"),
    EmailCfg(id='EFTA01782788', author=UNKNOWN_GIRL, highlight_quote='I need 21 24, wiling to travel and work hard', truncate_to=NO_TRUNCATE),
    EmailCfg(
        id='EFTA01024118',
        author=YULIA_DOROKHINA,
        author_reason='juliador89@mail.ru visible in verticle text',
        highlight_quote='I sent you nude pictures, sexy videos even masturbation',
        truncate_to=1_900,
    ),
    EmailCfg(
        id='EFTA01035876',
        author=YULIA_DOROKHINA,
        author_uncertain='"Yulia" in reply',
        is_interesting=5,
        note=f'looking for a job under {JIDE_ZEITLIN}',
        show_with_name=JIDE_ZEITLIN,
    ),
    EmailCfg(
        id='EFTA01036212',
        author=YULIA_DOROKHINA,
        author_uncertain='"Yulia"',
        note=f"Epstein wants {YULIA_DOROKHINA} to travel on short notice",
        truncate_to=NO_TRUNCATE,
    ),
    EmailCfg(id='EFTA01025400', author=YULIA_DOROKHINA),
    EmailCfg(id='EFTA01025734', author=YULIA_DOROKHINA, truncate_to=1_300),
    EmailCfg(id='EFTA01024680', author=YULIA_DOROKHINA, author_uncertain='thread'),
    EmailCfg(id='EFTA01024729', author=YULIA_DOROKHINA, author_uncertain='thread'),
    EmailCfg(id='EFTA02634523', author=YULIA_DOROKHINA, author_uncertain='"Yulia"'),
    EmailCfg(id='EFTA01028241', author=YULIA_DOROKHINA, author_uncertain='"Yulia" in other emails in thread', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA01026136', author=YULIA_DOROKHINA, highlight_quote='send the masturbation video', truncate_to=1_050),

    # Recipients
    EmailCfg(
        id='EFTA02223525',
        recipients=[ANNA_KASATKINA, BELLA_KLEIN, JANUSZ_BANASIAK],
        recipient_uncertain=JULIA_SANTOS_REDDIT_URL,
        truncate_to=800
    ),
    EmailCfg(
        id='EFTA01984912',
        recipients=[ANNABELLE_NEILSON],
        author_reason='signature',
        duplicate_ids=['EFTA02421743'],
        dupe_type='quoted',
        highlight_quote="a few of my girls, who would be perfect for the job but are unfortunately past their sell by date",
        is_interesting=4,
    ),
    EmailCfg(id='EFTA01840139', recipients=[GULSUM_OSMANOVA], author_reason='"GULSUM" in text'),
    EmailCfg(id='EFTA02470883', recipients=[YULIA_DOROKHINA]),
    EmailCfg(
        id='EFTA00997627',
        highlight_quote='you will be introduced to more gorgeous Alicas, i promise',
        recipients=[MARIA_PRUSAKOVA],
        recipient_uncertain='Kind regards/Cordialement in signature',
    ),
    EmailCfg(id='EFTA01904318', recipients=[MARIA_PRUSAKOVA], recipient_uncertain=PRUSAKOVA_REDDIT_URL),
    EmailCfg(id='EFTA00719146', recipients=[MARIA_PRUSAKOVA], recipient_uncertain='Clifford Chance, could be Miranda'),
    EmailCfg(id='EFTA00681554', recipients=[OLGA_PONOMAR_BECKER]),
    EmailCfg(id='EFTA02669915', recipients=[OLGA_PONOMAR_BECKER]),
    EmailCfg(
        id='EFTA01889182',
        highlight_quote="I had my first voluntary playing with a girl and guy",
        is_interesting=10,
        note=f'"Olympic snowboarder" is {MARIA_PRUSAKOVA} who seems to have entered Epstein world at this time',
        recipients=[MIRANDA_MAKO],
        recipient_uncertain=True,
        url='https://www.reddit.com/r/Epstein/comments/1r38kvr/disturbing_email_thanking_epstein_for_opening/',
    ),
    EmailCfg(
        id='EFTA01857628',
        is_interesting=10,
        note='"igrushki" means "toys" in Russian',
        recipients=[RENATA_BOLOTOVA],
        recipient_uncertain=True,
        url='https://x.com/FlippersUpNow/status/2023457206109155345',
    ),
    EmailCfg(
        id='EFTA00857669',
        is_interesting=10,
        note=f"{SANITA} is maybe the only great girl with right thinking in the entire Epstein files",
        recipients=[SANITA],
        truncate_to=NO_TRUNCATE,
    ),
    EmailCfg(id='EFTA00738485', recipients=[STEVEN_VICTOR_MD], truncate_to=640),
    EmailCfg(
        id='EFTA02560884',
        is_interesting=10,
        note=f"is Epstein drafting {SVETLANA_POZHIDAEVA}'s romantic responses to {JOSHUA_FINK} {QUESTION_MARKS}",
        recipients=[SVETLANA_POZHIDAEVA],
        recipient_uncertain=f"{JOSHUA_FINK} texts",
    ),
    EmailCfg(
        id='EFTA02543909',
        author_reason='p.selena@yahoo.com in replies',
        is_interesting=10,
        note=f'{SVETLANA_POZHIDAEVA}\'s relationship with "J" ({JOSHUA_FINK}?) and "B" {QUESTION_MARKS}',
        recipients=[SVETLANA_POZHIDAEVA],
    ),
    EmailCfg(
        id='EFTA00937556',
        is_interesting=20,
        note=f"looks like Epstein coaching {SVETLANA_POZHIDAEVA} on how to respond to {JOSHUA_FINK}",
        recipients=[SVETLANA_POZHIDAEVA],
    ),
    EmailCfg(
        id='EFTA02447019',
        recipients=[SVETLANA_POZHIDAEVA],
        url='https://www.wsj.com/us-news/epstein-victim-svetlana-pozhidaeva-22f2ebf6',
    ),
    EmailCfg(
        id='EFTA00888467',
        is_interesting=10,
        note=f'very strange conversation about "Peter" (maybe {PETER_MANDELSON}?) and "mj" (maybe {HASSAN_JAMEEL}?)',
        recipients=[UNKNOWN_GIRL],
    ),
    EmailCfg(id='EFTA00897668', recipients=[UNKNOWN_GIRL], entity_names=[JEAN_LUC_BRUNEL, JEFFREY_EPSTEIN, UNKNOWN_GIRL]),
    EmailCfg(id='EFTA00848644', recipients=[UNKNOWN_GIRL], highlight_quote='take a selfie of your pussy and send'),
    EmailCfg(
        id='EFTA01026268',
        author_reason='juliador89®mail.ru is unredacted',
        is_interesting=10,
        note=f"Epstein pressuring {YULIA_DOROKHINA} to find girls in Russia and send him nude pics and videos",
        recipients=[YULIA_DOROKHINA],
        truncate_to=3_100,
    ),
    EmailCfg(id='EFTA01024839', recipients=[YULIA_DOROKHINA], recipient_uncertain='part of thread'),
    EmailCfg(id='EFTA02276109', recipients=[YULIA_DOROKHINA], recipient_uncertain='"Yulia"'),

    EmailCfg(id='EFTA00642027', show_with_name=IRINA_STREMYAKOVA),
    EmailCfg(id='EFTA00642030', show_with_name=IRINA_STREMYAKOVA),

    # Descriptions
    EmailCfg(id='EFTA00078209', note='allegations about Russian organized crime, sex trafficking', is_interesting=8, truncate_to=8_500),
    EmailCfg(id='EFTA01648951', note=f'allegations against Trump, {HOWARD_LUTNICK}, Glen Dubin, {LEON_BLACK}, {JES_STALEY}'),
    EmailCfg(id='EFTA00950368', note='"any [girl] friends for me?"', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA00363992', note=f"car rental for {MARIANA_IDZKOWSKA}", show_with_name=MARIANA_IDZKOWSKA),
    EmailCfg(id='EFTA01814983', note=f"Epstein and {NICOLE_JUNKERMANN} used to date", show_with_name=NICOLE_JUNKERMANN),
    EmailCfg(id='EFTA02049364', note='Epstein arranging for healthcare for five girls', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA02209622', note=f'flight to Riga for {LASMA_KUHTARSKA}', show_with_name=LASMA_KUHTARSKA, truncate_to=600),
    EmailCfg(id='EFTA02199773', note=f'flight for {LASMA_KUHTARSKA}', show_with_name=LASMA_KUHTARSKA, truncate_to=600),
    EmailCfg(id='EFTA00968086', note='request for help for a Juilliard student', url=DITE_ANATA_JUILLIARD_URL),
    EmailCfg(
        id='EFTA00883738',
        is_interesting=11,
        note=f'Epstein recruiter {DASHA_GRUPMAN} looking to spend $50,000 to rent a townhouse for "diplomats"',
        show_with_name=DASHA_GRUPMAN,
    ),
    DocCfg(
        id='EFTA00009622',
        background_color='black',
        date='2006-07-19',
        display_text=EFTA00009622_TEXT,
        is_interesting=10,
        note='handwritten notes from a victim interview transcribed by Claude AI',
        show_full_panel=True,
        truncate_to=(1_500, 2_350),
    ),
    EmailCfg(
        id='EFTA00577409',
        date='2003-06-01',
        date_uncertain='just a guess, string is 4501 which is NULL in Microsoft Outlook',
        note='Epstein and Ghislaine discuss girl "from donad trumps party" who blackmailed [someone]',
    ),
    EmailCfg(
        id='EFTA02007083',
        note=f"{BORIS_NIKOLIC} encourages {KIMBAL_MUSK} to ditch his girlfriend for Epstein's girl {JENNIFER_KALIN} (and he says yes)",
        truncate_to=NO_TRUNCATE,
    ),
    EmailCfg(
        id='EFTA00412260',
        author=LESLEY_GROFF,
        comment='very broken file',
        date='2012-05-25 19:51:20',
        is_interesting=True,
        note=f'emphasis quotes by {LESLEY_GROFF}',
        highlight_quote='Jeffrey was asking if you and "your friend" could come by and meet Peter',
        recipients=[None],
        truncate_to=(6_700, 7_450),
    ),
    EmailCfg(
        id='EFTA00438431',
        note=f"visa invitation for {KARYNA_SHULIAK} to visit {QUESTION_MARKS}",
        recipients=[LESLEY_GROFF],
        show_with_name=KARYNA_SHULIAK,
    ),
    EmailCfg(
        id='EFTA00438475',
        highlight_quote="it will be best for Karyna to travel as Crew member",
        is_interesting=True,
        show_with_name=KARYNA_SHULIAK,
    ),

    # Katya Gusarova
    EmailCfg(id='EFTA00695655', author=EKATERINA_GUSAROVA, comment='related to EFTA00680327'),
    EmailCfg(
        id='EFTA00959489',
        highlight_quote='she is a little freaked by the age difference',
        is_interesting=6,
        note=f'girl is {EKATERINA_GUSAROVA}, "pro or civilian?"',
        show_with_name=EKATERINA_GUSAROVA,
        truncate_to=590,
    ),
    EmailCfg(
        id='EFTA00921172',
        highlight_quote="We had sex,I did massage for u non-stop,I took a bath with u and your girls even ,if I don't like it",
    ),
    EmailCfg(
        id='EFTA02037406',
        is_interesting=True,
        note=f"{STEVE_TISCH}, {EKATERINA_GUSAROVA}, {JEAN_LUC_BRUNEL} attending",
        show_with_name=EKATERINA_GUSAROVA,
    ),
    EmailCfg(
        id='EFTA00680327',
        author=EKATERINA_GUSAROVA,
        highlight_quote="Steve Tisch didn't email me yet",
        is_interesting=True,
        truncate_to=1_000,
    ),
    EmailCfg(id='EFTA00657216', highlight_quote='Is Katya coming over?', note=f'"Katya" is {EKATERINA_GUSAROVA}', truncate_to=600),
    EmailCfg(id='EFTA00959850', highlight_quote="send me a number to call I dont like records of these conversations"),

    # Lucrezia
    EmailCfg(id='EFTA01785808', recipients=[LUCREZIA_CAMPONOVO], recipient_uncertain='Italian language'),

    # Quotes
    EmailCfg(
        id='011908_3',
        highlight_quote='sex trafficking allegations have stopped us from working with • your agency for the past 5-6 years',
        is_interesting=5,
    ),
    EmailCfg(
        id='EFTA00740146',
        highlight_quote='I might want to fund an exhibition entitled statutory',
        is_interesting=3,
    ),
    EmailCfg(
        id='EFTA02504370',
        highlight_quote=f'lovely girl with financial troubles',
        recipients=[KIRA_DIKHTYAR],
        recipient_uncertain='"Sent from AOL Mobile Mail"',
        truncate_to=NO_TRUNCATE,
    ),
    EmailCfg(
        id='EFTA00465926',
        highlight_quote='we will cancel this ticket prior to departure',
        note='Paris, possible immigration fraud',
        truncate_to=350,
    ),
    EmailCfg(
        id='EFTA01022353',
        highlight_quote='she said she was 14-15 yo',
        note='(George Models is basically a porn site)',
    ),
    EmailCfg(
        id='EFTA01885139',
        highlight_quote='Kimbal really like Jen;-) We will need to distract the ex (any spare ambien);-)',
        note=f'{JENNIFER_KALIN}, Epstein\'s girl whom {KIMBAL_MUSK} soon dated, jokes about drugging women with Ambien',
    ),
    EmailCfg(
        id='EFTA02415420',
        highlight_quote="I have a friend of Putin,s , should i ask him?",
        is_interesting=20,
    ),
    EmailCfg(
        id='EFTA02555750',
        highlight_quote='suspend any billing from now on until further notification from you or the model',
        note=f"who's \"the model\" {JEAN_LUC_BRUNEL} is \"billing\" {JOSHUA_FINK} for?",
    ),
    EmailCfg(
        id='EFTA00878421',
        highlight_quote="she knows that Jesus watches over her. and he helped save her life. Whoops",
        is_interesting=10,
        recipients=[NADIA_MARCINKO],
        recipient_uncertain='https://archive.ph/Qa6vU',  # https://www.nybooks.com/articles/2026/03/26/the-devil-himself-jeffrey-epstein-enright/
    ),
    EmailCfg(
        id='EFTA00935996',
        highlight_quote='I treat you betteer than all the other wives',
        is_interesting=True,
        note='implicit threat of deportation',
        recipients=[RENATA_BOLOTOVA],
        recipient_uncertain=SNEAKY_DOG,
    ),
    EmailCfg(
        id='EFTA02515671',
        highlight_quote='she met this Congressman recently who, from what I unde=stood gives her everything, a private driver, bodyguard',
        is_interesting=True,
    ),
    EmailCfg(id='EFTA00478987', highlight_quote='Designer babies', show_with_name=BRYAN_BISHOP, truncate_to=925),
    EmailCfg(id='EFTA01004801', highlight_quote="Here is a deck about my designer baby project"),
    EmailCfg(id='EFTA01004795', visible_in_id='EFTA01004801'),
    EmailCfg(id='EFTA00582316', highlight_quote="+ 5 models who are the serving girls", is_interesting=True),
    EmailCfg(id='EFTA00066441', highlight_quote='Daniel Siad, whom Jean Luc describes as a "scout" or recruiter of girls', is_interesting=True, is_in_chrono=False),
    EmailCfg(id='EFTA01891832', highlight_quote="Anya, do u have any 20 years old girl for Jeffrey in Kiev?"),
    EmailCfg(id='EFTA00971793', highlight_quote='Attached is resume of Lutnick nanny', note=f"why does Epstein need a nanny?"),
    EmailCfg(id='EFTA01965732', highlight_quote='facilictating his illicit trysts, with married women, to being asked to provide adderall fro bridge tournamnts', is_interesting=5),
    EmailCfg(id='EFTA01768670', highlight_quote='find girls for the agency', note=f'but {BORIS_NIKOLIC} is a "biotech investor"...', is_interesting=True),
    EmailCfg(id='EFTA01905320', highlight_quote='girls and i are going to see elon musk at space x tomorrow'),
    EmailCfg(id='EFTA00985636', highlight_quote='Gonna meet Steve Tisch next week for a dinner', is_interesting=True, recipients=[UNKNOWN_GIRL]),
    EmailCfg(id='EFTA01803353', highlight_quote='having problems with regina', note='(Ramsey?)', is_interesting=True),
    EmailCfg(id='EFTA00772798', highlight_quote="how old was she in 99 then?", note='Epstein tells Ghislaine that Giuffre was 17'),
    EmailCfg(id='EFTA00950394', highlight_quote='how old will you go?'),
    EmailCfg(id='EFTA02551185', highlight_quote='I believe this girl belongs to Jeffery already'),
    EmailCfg(id='EFTA02504630', highlight_quote="I found at least 3 very good young poor"),
    EmailCfg(id='EFTA02499884', highlight_quote='I gave another girl to kimball and he is thrilled', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA02557757', highlight_quote="I have a girl Sana working half time/who by the way you'd like", is_interesting=True),
    EmailCfg(id='EFTA00771856', highlight_quote="I know 23 is on the old side for you", note=quote("she's 23 but oozes sex"), truncate_to=3_000),
    EmailCfg(id='EFTA01888497', highlight_quote="I think I am perverted", is_interesting=True),
    EmailCfg(id='EFTA00986371', highlight_quote="I'm going to have a lunch right now with Steve Tisch:) lol", is_interesting=True, recipients=[UNKNOWN_GIRL]),
    EmailCfg(id='EFTA01740839', highlight_quote='is the invitation for Sultan AND his wife?', note='note capital "AND"', is_interesting=True),
    EmailCfg(id='EFTA01767237', highlight_quote='is 24 too old for you?', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA00854166', highlight_quote='kazak contract will be ready for your review', truncate_to=1_100),
    EmailCfg(id='EFTA00994380', highlight_quote='please confirm $500 to Sergey Pozhidaev', truncate_to=500),
    EmailCfg(id='EFTA00894079', highlight_quote='say hi to Snow White'),
    EmailCfg(id='EFTA00775255', highlight_quote='she is 20 years old but she looks younger', non_participants=[BROCK_PIERCE]),
    EmailCfg(id='EFTA00366629', highlight_quote='stunning girls to bring over drinks when your next available'),
    EmailCfg(id='EFTA01895036', highlight_quote='svetlana will be in paris 17-20', note=f"Epstein invites {ELON_MUSK} to Paris"),
    EmailCfg(id='EFTA02415943', highlight_quote='tell geir, she is serious , not a toy, . toys are also availble', truncate_to=700, is_interesting=5),
    EmailCfg(id='EFTA02387676', highlight_quote="thats the closest i get to karyna providing me new pussy"),
    EmailCfg(id='EFTA00628544', highlight_quote="the water gazelle is really stunning...what a beautiful and smart girl!", note=f'"water gazelle\'s" name is "Jane"'),
    EmailCfg(id='EFTA00953438', highlight_quote="how is my water gaselle???", note=f'"water gazelle\'s" name is "Jane"'),
    EmailCfg(id='EFTA00465937', highlight_quote="there are 3 teenage girls there. ! Let them get out!"),
    EmailCfg(id='EFTA00908180', highlight_quote='two cinderellas', is_interesting=True),
    EmailCfg(id='EFTA01930285', highlight_quote='ukraine upheaval should provide many opportunites'),
    EmailCfg(id='EFTA00751119', highlight_quote='Valdson to teach girls how to serve', is_interesting=True),
    EmailCfg(id='EFTA00631354', highlight_quote='we need to figure out pills for <REDACTED>'),
    EmailCfg(id='EFTA00682682', highlight_quote='Working girl?', truncate_to=300, duplicate_ids=['EFTA00680779'], dupe_type='redacted'),
    EmailCfg(id='EFTA01995972', highlight_quote='you are meeting elon tmr for lunch', is_interesting=20),
    EmailCfg(id='EFTA01754444', highlight_quote="You want me to introduce to a young beautiful Russian model ,right?"),
    EmailCfg(id='EFTA01930501', highlight_quote="Your littlest girl was a little naughty"),
    EmailCfg(id='DropSite 2006-05-29 1329', highlight_quote='I am giving the little girl a modeling\n> lesson', is_interesting=True),

    # Dubins
    EmailCfg(id='EFTA00902125', author=CELINA_DUBIN, author_reason='quoted reply', is_in_chrono=False),
    EmailCfg(id='EFTA02559808', note=f"{EVA_DUBIN} delivering amphetamines (adderall)", is_interesting=10, truncate_to=200),
    EmailCfg(id='EFTA01953412', note=f'{EVA_DUBIN} suggests Epstein endow "The Epstein Floor For Women" at Mt. Sinai'),
    EmailCfg(id='EFTA00747141', note=f'photo shoot for 11 year old {CELINA_DUBIN}', truncate_to=NO_TRUNCATE, is_in_chrono=False),
    EmailCfg(id='EFTA00747461', note=f'photo shoot for 11 year old {CELINA_DUBIN}', truncate_to=NO_TRUNCATE, is_in_chrono=False),
    EmailCfg(id='EFTA00747744', note=f'photo shoot for 11 year old {CELINA_DUBIN}', truncate_to=NO_TRUNCATE, is_in_chrono=False),
    EmailCfg(id='EFTA01055103', note=f"looks like someone stole {CELINA_DUBIN}'s gift card", show_with_name=CELINA_DUBIN, is_in_chrono=False),
    EmailCfg(id='EFTA00913853', recipients=[EVA_DUBIN]),

    # Faith Kates
    EmailCfg(id='EFTA02512317', recipients=[FAITH_KATES], author_reason='"faith,"', note="Epstein suggests Next Models take on a girl"),

    # Josh Fink
    EmailCfg(
        id='EFTA01868066',
        # author=SVETLANA_POZHIDAEVA,
        # author_uncertain=f"{JOSHUA_FINK} + Sent from Blackberry",
        note=f'impersonating [someone] talking to {JOSHUA_FINK} ("Dana" could be typo of "Lana", as {SVETLANA_POZHIDAEVA} and Josh Fink dated)',
        duplicate_ids=['EFTA01995523'],
        is_interesting=20,
    ),
    EmailCfg(
        id='EFTA01877084',
        comment='https://x.com/HansMahncke/status/2024351830998994979',
        note=f'Epstein and {JEAN_LUC_BRUNEL} "managing" {JOSHUA_FINK}\'s relationship with {SVETLANA_POZHIDAEVA}',
        is_interesting=10,
        truncate_to=500,
    ),
    EmailCfg(
        id='EFTA00704924',
        note=f"stalking Josh Fink (attachment is pic of {JOSHUA_FINK} and {FILIPA_PEROVIC} who later married)",
        show_with_name=JOSHUA_FINK,
    ),
    EmailCfg(
        id='EFTA02217672',
        note=f"{DAVID_L_NEUHAUSER} is raising money for a {JOSHUA_FINK} fund, promises Epstein he won't reveal they're talking",
        is_interesting=True,
    ),
    EmailCfg(
        id='EFTA01907281',
        note=f"Epstein asks about {JOSHUA_FINK}, pretends it's because {TANCREDI_MARCHIOLO} asked *him* (Epstein asked Marchiolo)",
        show_with_name=JOSHUA_FINK,
        is_interesting=10,
    ),
    EmailCfg(
        id='EFTA01858707',
        author=SVETLANA_POZHIDAEVA,
        highlight_quote='How is the marriage plan going',
        note=f'"JF" is {JOSHUA_FINK}',
    ),
    EmailCfg(id='EFTA00937981', note=f"Epstein looking for {JOSHUA_FINK} (again)", is_interesting=10),
    EmailCfg(id='EFTA00668344', note=f"Epstein looking for {JOSHUA_FINK} (again)", is_interesting=10),
    EmailCfg(id='EFTA01856467', note=f"Epstein looking for {JOSHUA_FINK} (again)", is_interesting=10, truncate_to=NO_TRUNCATE),

    # Zlata
    EmailCfg(id='EFTA00690497', note=f'"young woman" is {ZLATA_RYBAROVA}', show_with_name=ZLATA_RYBAROVA),
    EmailCfg(id='EFTA00628068', show_with_name=ZLATA_RYBAROVA),
    EmailCfg(id='EFTA00657593', highlight_quote="The girl I have for you is clever, ambitious, lot of fun, really big time crazy :)"),

    # Descriptions
    EmailCfg(
        id='EFTA02627361',
        is_interesting=5,
        note=f'Epstein sending {YULIA_DOROKHINA} {QUESTION_MARKS} to {JIDE_ZEITLIN}',
        recipients=[JIDE_ZEITLIN],
        recipient_uncertain=True,
        show_with_name=YULIA_DOROKHINA,
    ),
    EmailCfg(
        id='EFTA02434682',
        note=f"textbook example of Epstein and {JEAN_LUC_BRUNEL} using girls to close deals",
        is_interesting=10,
        truncate_to=1_000,
    ),
    EmailCfg(id='EFTA01849371', note=f"{SVETLANA_POZHIDAEVA} meets Larry Fink", truncate_to=500),
    # EmailCfg(id='EFTA01849371', note=f"{SVETLANA_POZHIDAEVA} meets Nat Rothschild", show_with_name=SVETLANA_POZHIDAEVA),
    EmailCfg(id='EFTA02142175', note=f"{DARREN_INDYKE} meeting {JEAN_LUC_BRUNEL} at Karin Models office"),
    EmailCfg(id='EFTA01840103', note="Epstein apparently suggesting amphetamines (adderall)", is_interesting=10),
    EmailCfg(id='EFTA01987855', note=f'Epstein, Brunel, and {SULTAN_BIN_SULAYEM} very interested in a Liberian sex scandal'),
    EmailCfg(id='EFTA01817903', note=f'Epstein, Brunel, and {SULTAN_BIN_SULAYEM} sharing news of a Liberian sex scandal', is_interesting=10),
    EmailCfg(id='EFTA01818540', note=f'Epstein forwarding news of the Liberian sex scandal to {JES_STALEY}', truncate_to=415),
    EmailCfg(id='EFTA01140210', note='Epstein asks about fake Instagram followers'),
    EmailCfg(id='EFTA01854125', note=f'Epstein says to {HENRY_JARECKI} "you torture, and mistreat each" girl', is_interesting=10),
    EmailCfg(id='EFTA01936438', note=f'Epstein\'s standard password might be "MVEMJSNUP"', is_interesting=10),
    EmailCfg(id='EFTA00383769', note=f"Epstein attempting to recruit Frederika Finkelstein", is_in_chrono=False),
    EmailCfg(id='EFTA00658028', note=f'{FAITH_KATES} trying to get a modeling contract for "Regina"?'),
    EmailCfg(id='EFTA00855566', note=f"introducing {SANITA}", truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA01145923', note=f"{JEAN_LUC_BRUNEL} modeling contract for {MC2_MODEL_MGMT}"),
    EmailCfg(id='EFTA00697420', highlight_quote="Jeffrey please help me here is she a hooker", note=f'stepping out with "Heidi"'),
    EmailCfg(id='EFTA00932166', note=f"{MARK_ZEFF}'s letter of visa recommendation for South African girl in EFTA00537633"),  # TODO: make it an attachment?
    EmailCfg(id='EFTA02609062', note=f"{MASHA_DROKOVA} is assembling a team", is_interesting=10),
    EmailCfg(id='EFTA02557291', note='possibly recruiting girls'),
    EmailCfg(id='EFTA01990860', note=f"{PRINCE_ANDREW}'s public denial draft"),
    EmailCfg(
        id='EFTA01811230',
        note=f'"Renat" is probably {RENATA_BOLOTOVA}, {REDACTED} might be "Irina" or {SVETLANA_POZHIDAEVA}',
        duplicate_ids=['EFTA00732294'],
    ),
    EmailCfg(id='EFTA00927927', note=f"{RENATA_BOLOTOVA} possibly talking about recruiting girls"),
    EmailCfg(
        id='EFTA01816788',
        highlight_quote="she 26, russian, clevere beautiful, trustworthy and yes she has your email",
        is_interesting=9,
        note=f"Russian girl for {PRINCE_ANDREW}",
        truncate_to=370,
    ),
    EmailCfg(id='EFTA00876739', note=f'scouting girls in Ukraine {QUESTION_MARKS}'),
    EmailCfg(id='EFTA00901905', note="smoking in the house oh no!"),
    EmailCfg(
        id='EFTA00914505',
        duplicate_ids=['EFTA01999588'],
        note=f"Epstein can't go to \"nats\" but (because?) {SVETLANA_POZHIDAEVA} and {JOSHUA_FINK} will be there",
        show_with_name=SVETLANA_POZHIDAEVA,
    ),
    EmailCfg(
        id='EFTA01798715',
        is_interesting=10,
        note=f"{SVETLANA_POZHIDAEVA} taking an interest in {JOSHUA_FINK}'s investments in Eritrea in between hair gigs",
    ),
    EmailCfg(id='EFTA00572157', note='translation: "Congratulations on the new addition!!! What did you name the little miracle?" (seems to be about a cat)'),
    EmailCfg(id='EFTA00631762', note="visa problems for Epstein's South African friend"),
    EmailCfg(id='EFTA00376832', show_with_name=MARIANA_IDZKOWSKA),
    EmailCfg(id='EFTA02702141', truncate_to=NO_TRUNCATE, comment=ELON_MUSK),
    EmailCfg(id='EFTA00819508', truncate_to=NO_TRUNCATE, comment=JULIA_SANTOS),
    EmailCfg(id='EFTA00460312', truncate_to=NO_TRUNCATE, comment=JULIA_SANTOS),
    EmailCfg(id='EFTA02664956', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA00689698', truncate_to=NO_TRUNCATE),
    EmailCfg(id='EFTA00878255', comment=BORIS_NIKOLIC),
    EmailCfg(id='EFTA02538269', comment=BORIS_NIKOLIC, duplicate_ids=['EFTA01866636']),
    EmailCfg(id='EFTA00736518', comment=JES_STALEY + ' beauty and the beast'),
    EmailCfg(id='EFTA02344845', comment=JULIA_SANTOS),
    EmailCfg(id='EFTA02491007', comment=JULIA_SANTOS),
    EmailCfg(id='EFTA00633284', comment=JULIA_SANTOS),
    EmailCfg(id='EFTA00664521', comment=JULIA_SANTOS),
    EmailCfg(id='EFTA00997666', comment=JULIA_SANTOS),
    EmailCfg(id='EFTA00964428', comment=JULIA_SANTOS + ' Valdson'),
    EmailCfg(id='EFTA02398135', comment=JULIA_SANTOS + ' "Sochi"'),
    EmailCfg(id='EFTA00766770'),

    # Jean Luc
    EmailCfg(id='EFTA00660742', author=JEAN_LUC_BRUNEL, author_reason='reply', non_participants=[SVETLANA_POZHIDAEVA]),

    # Ramsey
    EmailCfg(
        id='EFTA00743526',
        is_interesting=True,
        note=f"Epstein and {RAMSEY_ELKHOLY} trying to get a Next Models contract for Regina",
        truncate_to=(800, 2_160),
    ),
    EmailCfg(
        id='EFTA00902144',
        note=f"{RAMSEY_ELKHOLY} severing ties with Regina who is dating the same boyfriend as {RUSLANA_KORSHUNOVA} was before her death",
    ),
    DocCfg(id='EFTA01130064', attached_to_email_id='EFTA00902144'),

    # Text msg
    TextCfg(
        id='EFTA00509258',
        highlight_quote="The kid » couldn't have done bikini wax cause hair are « too short",
        note=f'grooming a new girl with a "pornhub introduction"',
        recipients=['Harry Fish', 'Karin', EVA_DUBIN, TERJE_ROD_LARSEN],
    ),

    # Asia
    EmailCfg(
        id='EFTA02046979',
        is_interesting=True,
        note=f"flights for Kimberly Ko and {WANDI_ZHU}",
        show_with_name=WANDI_ZHU,
        truncate_to=(1_140, 1_800),
    ),
    EmailCfg(
        id='EFTA02047748',
        is_interesting=15,
        note=f"Epstein's travel booker at Amex {NATALIA_MOLOTKOVA} holds a Russian passport (and his Chinese girlfriends lost their passports)",
        truncate_to=800,
    ),

    # Jean Luc
    EmailCfg(id='EFTA01885240', note=f'"little russian girl" is {IRINA_STREMYAKOVA}', show_with_name=IRINA_STREMYAKOVA),

    # Virginia Giuffre
    EmailCfg(id='EFTA00906567', highlight_quote="i need to totally discredit virgina roberts", truncate_to=AUTO),
    EmailCfg(id='EFTA01159195', note=f'criminal history of {RONALD_EPPINGER} whom Epstein calls {VIRGINIA_GIUFFRE}\'s "pimp"', truncate_to=500),

    # Sarah Kellene
    EmailCfg(id='EFTA02412698', author=SARAH_KELLEN),
    EmailCfg(id='EFTA00735965', recipients=[SARAH_KELLEN], recipient_uncertain='Carstensen', is_in_chrono=False),

    # Immigration
    EmailCfg(
        id='EFTA02312343',
        note=f"email about sham marriage visa issues, possibly from {RENATA_BOLOTOVA}'s spouse",
        is_interesting=10,
    ),
    EmailCfg(
        id='EFTA00966384',
        author=NADIA_MARCINKO,
        highlight_quote="Aviloop. As payment for services, to show income for the visa",
        note='probably evidence of immigration visa fraud',
    ),
    DocCfg(id='EFTA02312343_1', note='translation of visa email', attached_to_email_id='EFTA02312343', show_full_panel=True),
    EmailCfg(id='EFTA00671065', author=UNKNOWN_GIRL),
    EmailCfg(id='EFTA00746255', author=UNKNOWN_GIRL, highlight_quote="i would love to take photos of you in a snow white costume", is_interesting=True),
    EmailCfg(id='EFTA02652017', note="inquiry about someone's immigration asylum application", is_interesting=True),
    EmailCfg(id='EFTA00637127', note=f"{CECILE_DE_JONGH} helping with girls' visa issues"),
    EmailCfg(id='EFTA00695768', note=f"{CECILE_DE_JONGH} helping with girls' visa issues", is_interesting=4),
    EmailCfg(id='EFTA00458715', show_with_name=MASHA_DROKOVA),
    EmailCfg(id='EFTA00349192', note='contains visa info'),
    blaine_letter('019086', date='2015-05-27', suffix='naming various Putin puppet regimes', show_full_panel=True),
    blaine_letter('019474', date='2015-05-29'),
    blaine_letter('019476', date='2015-06-01'),
    immigration_letter(
        'EFTA00314931',
        TERJE_ROD_LARSEN,
        '2017-06-08',
        'speaking for the International Peace Institute',
        comment='PR job description + size of redaction is probably Drokova',
        show_with_name=MASHA_DROKOVA,
    ),
    immigration_letter('EFTA02389172', 'Michael Harrigan'),
    immigration_letter('EFTA00308104', MARTIN_NOWAK, '2017-06-06', f'possibly about {MASHA_DROKOVA} visa', show_with_name=MASHA_DROKOVA),
    immigration_letter('EFTA00589797', TERJE_ROD_LARSEN, '2015-05-02'),
    immigration_letter('EFTA01086449', ARIANE_DE_ROTHSCHILD, show_with_name=SVETLANA_POZHIDAEVA, comment='"Economic Forum" is probably St. Petersburg'),
    immigration_letter('EFTA01143800', None, show_with_name=SVETLANA_POZHIDAEVA),
    immigration_letter('EFTA00537633', MARK_ZEFF, '2012-03-19', 'about SLK Designs, someone in interior design industry'),
]
