from epstein_files.documents.config.config_builder import fbi_defense_witness, fbi_interview, fbi_tip, fbi_report, grand_jury, letter, memo
from epstein_files.documents.config.doc_cfg import NO_TRUNCATE, SHORT_TRUNCATE_TO, DocCfg
from epstein_files.documents.config.email_cfg import EmailCfg
from epstein_files.people.names import *
from epstein_files.util.constant.strings import AUTO, CVRA, MINOR_VICTIM, REDACTED
from epstein_files.util.helpers.string_helper import join_truthy, quote
from epstein_files.util.logging import logger

FBI_REPORT_FIELDS = [
    'Approved By',
    'Case Agent Name',
    'Case ID #',
    'City',
    'Classified By',
    'Contact',
    'Country',
    'Date of Contact',
    'Date of Report',
    'Declassify On',
    'Derived From',
    'Drafted By',
    'Date/Time Received',
    'Details',
    'Field Office/Division',
    'Form Type',
    'Precedence',
    'SentinelCaseld',
    'SentToSentinel',
    'Source ID',
    'Squad',
    'State',
    'Synopsis',
    'Title',
    'Type of Contact',
]


def bop_doc(id: str, note: str = '', date: str = '', display_text: str = '', **kwargs) -> DocCfg:
    return DocCfg(
        id=id,
        author=BUREAU_OF_PRISONS,
        note=note,
        date=date,
        display_text=display_text,
        **kwargs
    )


def bop_memo(id: str, note: str, date: str = '', **kwargs) -> DocCfg:
    return memo(id, BUREAU_OF_PRISONS, note, date, **kwargs)


def bop_policy_doc(id: str, display_text: str, date: str = '') -> DocCfg:
    """Bureau of prison brochures, poliicy statements, etc."""
    return bop_doc(id, date=date, display_text=display_text)


def doj_doc(id: str, note: str, **kwargs) -> DocCfg:
    return DocCfg(id=id, note=note, author=DOJ, **kwargs)


def doj_memo(id: str, note: str, date: str = '', **kwargs) -> DocCfg:
    return memo(id, DOJ, note, date, **kwargs)


def fbi_internal(id: str, **kwargs) -> EmailCfg:
    return EmailCfg(id=id, author=FBI, recipients=[FBI], **kwargs)


def fbi_evidence_review(id: str) -> EmailCfg:
    return EmailCfg(id=id, author=FBI, recipients=[FBI, NYPD], note='summary of pictures and videos from Epstein computers')


def fincen_sar(id: str, bank: str, subject: str, activity: str, **kwargs) -> DocCfg:
    note = f"Suspicious Activity Report filed by {bank} about {subject} for {activity}"
    return DocCfg(id=id, author=FINCEN, note=note, **kwargs)


def usanys_internal_email(id: str, **kwargs) -> EmailCfg:
    return EmailCfg(id=id, author=USANYS, recipients=[USANYS], author_uncertain=True, **kwargs)


GOVERNMENT_CFGS = [
    DocCfg(
        id='024117',
        note=f"anti-money laundering (AML), Bank Secrecy Act (BSA), & terrorist financing (CFT) US law FAQ",
        is_interesting=True,
    ),
    DocCfg(
        id='EFTA00315076',
        date='2008-06-01',
        date_uncertain=True,
        note=f"visitor list during Epstein's 2009 incarceration in {PALM_BEACH}",
        show_full_panel=True,
    ),
    DocCfg(
        id='EFTA00306074',
        date='2008-06-01',
        date_uncertain=True,
        note=f"approved mail list during Epstein's 2009 incarceration in {PALM_BEACH}",
        show_full_panel=True,
    ),
    DocCfg(
        id='EFTA00173953',
        author=OCDETF,
        date='2015-05-18',
        is_interesting=20,
        note=f"heavily redacted report on Epstein's potential involvement in Caribbean drug money laundering, {MARIANA_IDZKOWSKA}'s name is unredacted",
        truncate_to=(7_700, 12_600),
    ),
    bop_doc(
        'EFTA00034357',
        "internal message about discovery of Epstein's body",
        '2019-08-10',
        background_color='red',
    ),
    bop_doc(
        'EFTA00034275',
        "initial form filed about Epstein's suicide attempt",
        '2019-07-23',
        comment='visible in EFTA00019348',
        is_interesting=False,
    ),
    bop_doc(
        'EFTA00019348',
        "report on Epstein's failed suicide attempt",
        '2019-08-02',
        highlight_quote='staff observed inmate Epstein, Jeffrey lying in the fetal position on the floor with a homemade fashioned noose around his neck',
        truncate_to=(7_500, 12_500),
    ),
    bop_doc('EFTA00035921', "Lieutenant's Logs", '2019-08-06'),
    bop_doc('EFTA00039153', 'List of Exhibits, Chapter 2', '2019-01-06'),
    bop_doc('EFTA00109163', 'Metropolitan Correctional Center forms showing Konstantin Ignatov', '2019-08-08', is_interesting=True),
    bop_doc('EFTA00120617', '"Prisoner Remand or Order to Deliver" forms', '2019-07-30'),
    bop_doc('EFTA00109783', 'prisoner assignments', '2019-08-03'),
    bop_doc('EFTA00109654', 'roster of inmates at Metropolitan Correctional Center', '2019-08-08'),
    bop_doc('EFTA00108533', 'roster of inmates at Metropolitan Correctional Center', '2019-07-23'),
    bop_doc('EFTA00108552', 'roster of inmates at Metropolitan Correctional Center', '2019-07-23'),
    bop_doc('EFTA00039025', "report on death of Jeffrey Epstein", '2023-06-22', is_interesting=10),
    bop_doc('EFTA00039190', 'Special Housing Units', '2016-11-23', is_interesting=False),
    bop_memo('EFTA00036136', 'camera project'),
    bop_memo('EFTA00143071', 'Epstein and his cellmate Efrain Reyes', is_interesting=True),
    bop_policy_doc('EFTA00120459', 'handwritten log of prisoner movements', date='2019-08-09'),
    bop_policy_doc('EFTA00039227', 'Inmate Discipline Program Statement'),
    bop_policy_doc('EFTA00039295', 'Inmate Telephone Privileges Program Statement'),
    bop_policy_doc('EFTA00039312', 'Program Statement / Memo about BOP Pharmacy Program'),
    bop_policy_doc('EFTA00039351', 'Program Statement / Memo about BOP Pharmacy Program', date='2004-11-17'),
    bop_policy_doc('EFTA00039156', 'Standards of Employee Conduct'),
    DocCfg(
        id='EFTA01125108',
        author='DHS',
        note=f'receipt for I129 Petition for a Nonimmigrant Worker filed by Sublime Art LLC, {ARDA_BESKARDES}',
        is_interesting=True,
    ),
    DocCfg(
        id='EFTA00164939',
        author=DOJ,
        date='2025-09-01',
        date_uncertain='approximate',
        duplicate_ids=['EFTA01660622'],
        note='Powerpoint summary of Epstein investigation by Child Sex Trafficking Task Force',
        is_interesting=10,
    ),
    doj_doc('EFTA00025091', f"arrest warrant and other discovery materials"),
    doj_doc('EFTA00009809', f"sealed indictment of Jeffrey Epstein", date='2019-07-02', is_interesting=2),
    doj_memo('EFTA02731039', f'prosecution memo naming {LESLEY_GROFF}', is_interesting=10),
    doj_memo('EFTA02731200', "potential prosecution of Epstein's assistant", is_interesting=10, truncate_to=(14_000, 18_500)),
    doj_memo('EFTA02731082', "investigation into Epstein's co-conspirators"),
    doj_memo('EFTA02731226', f"charging {GHISLAINE_MAXWELL} with additional offenses", '2021-03-14'),
    DocCfg(
        id='EFTA00157613',
        author=DOJ,
        date='2021-06-08',
        note=f"witness prep of Juan Alessi, Epstein's former house manager in Palm Beach describing Trump's visits",
        truncate_to=(6_000, 7_000),
        show_full_panel=True,  # TODO: show pic
    ),
    DocCfg(
        id='EFTA00014822',
        date='1982-06-01',
        date_uncertain=True,
        note=f"fake Austrian passport with Saudi address under the name Marius Robert Fortelni found in Epstein's possession",
        show_image=True,
        url='https://nypost.com/2025/12/23/us-news/jeffrey-epsteins-fake-austrian-passport-pictured-in-latest-doj-document-dump/',
    ),
    DocCfg(id='EFTA02730741', author=DOJ, date='2025-05-01', date_uncertain=True, note="Evidence list for 50D-NY-3027571 Filtering On 'Type(s): 1B'"),
    DocCfg(id='EFTA02730486', author=DOJ, date='2025-05-01', date_uncertain=True, note="Evidence list for 50D-NY-3027571 Filtering On '1A'"),
    DocCfg(id='EFTA00040006', author=DOJ, date='2019-08-27', note='Personal History of Defendant Jeffrey Epstein + grand jury indictment'),
    DocCfg(id='EFTA00023055', author=FBI, note="evidence of notes left about newly recruited underage girls by girls giving massages"),
    DocCfg(id='EFTA01731217', author=FBI, note=f'requesting INS allow {NADIA_MARCINKO} be allowed to stay in the US because of an ongoing sex-trafficking case', is_interesting=True),
    DocCfg(id='EFTA00247131', author=FBI, note='search warrant for New York house', date='2019-07-07'),
    fbi_defense_witness('EFTA02730267', 'Malcolm Grumbridge', '2022-04-14'),
    fbi_defense_witness('EFTA02730477', 'Roderic Alexander', '2022-01-19'),
    fbi_defense_witness('EFTA02730271', None, '2022-03-22'),
    # FBI interviews
    fbi_interview(
        'EFTA00064309',
        'MCC camera technician',
        quote("Only one hard drive of the camera system was working at the time of [Epstein's death]"),
        '2020-03-12',
        highlight_quote='advised that he knew that by replacing both hard drives, the system would be wiped'
    ),
    fbi_interview(
        'EFTA00126948',
        f'{BUREAU_OF_PRISONS} personnel',
        highlight_quote='EPSTEIN claimed that his cellmate, NICHOLAS TARTAGLIONE, tried to take his life',
        truncate_to=(4_250, 5_500),
    ),
    fbi_interview(
        'EFTA01246710',
        PERRY_LANG,
        "Epstein's chef claims Donald Trump came to Epstein's house for dinner",
        is_interesting=10,
        truncate_to=(6_000, 7_500),
    ),
    fbi_interview(
        'EFTA02858481',
        'Jennifer Aros',
        'Epstein and Trump accuser',
        '2019-08-07',
        is_interesting=True,
        truncate_to=(16_500, 20_000),
    ),
    fbi_interview('EFTA01309589', ANTHONY_FIGUEROA, 'recruiting from high schools', '2020-08-27', is_interesting=True),
    fbi_interview('EFTA00174375', LUKE_D_THORBURN, f"lots of takes on Epstein, China, and {STEVE_BANNON}"),
    fbi_interview('EFTA00081226', MINOR_VICTIM),
    fbi_interview('EFTA00038915', MINOR_VICTIM, 'claims Epstein knew she was 14'),
    fbi_interview('EFTA00090602', STEVE_SCULLY, date='2019-08-09', show_full_panel=True),
    fbi_interview('EFTA01699136', f"{VIRGINIA_GIUFFRE} and other victims", f'"Turkish girl" might be {GULSUM_OSMANOVA}', date='2011-03-17'),
    fbi_interview('EFTA00101927', None, f"claims Glenn and {EVA_DUBIN}'s Swiss au pair was being held against her will"),
    fbi_interview('EFTA00159321', None, f'covers {PAOLO_ZAMPOLLI}, Epstein, and the possibility Epstein introduced Melania to Donald Trump'),
    # FBI reports
    fbi_report(
        '018872',
        non_participants=[
            BILL_GATES,
            BILL_RICHARDSON,
            EDUARDO_ROBLES,
            'Eliot Spitzer',
            GERALD_LEFCOURT,
            GLENN_DUBIN,
            JEAN_LUC_BRUNEL,
            # JOI_ITO,
            # LARRY_SUMMERS,
            LAWRANCE_VISOSKI,  # Just bc his deposition comes soon after
            MARK_EPSTEIN,
            MARTIN_NOWAK,
            MORTIMER_ZUCKERMAN,
            PRINCE_ANDREW,
            SECURITIES_AND_EXCHANGE_COMMISSION,
            STEVEN_HOFFENBERG,
            SVETLANA_POZHIDAEVA
        ],
    ),
    fbi_report('021569'),
    fbi_report('021434', is_valid_for_name_scan=False),
    fbi_report('019352', f"contains clippings of various press items about Epstein"),
    fbi_report(
        'EFTA00129085',
        'wiretap linking phone number in John Gotti / Gambino / Michael Bilotti investigation to phone in Epstein investigation',
        is_interesting=True,
    ),
    fbi_report('EFTA01688746'),
    fbi_report(
        'EFTA00164480',
        'Epstein death investigation (Powerpoint slides)',
        # background_color='dark_red',
        date='2019-09-01',
        date_uncertain='after death, before scheduled interviews Oct. 18th',
        is_interesting=4,
    ),
    fbi_report('EFTA00151754', 'declaration of Law Enforcement Officer for Victim of Trafficking', is_interesting=True),
    fbi_report('EFTA00173569', 'hack of FBI Epstein files repository by foreign actor', is_interesting=True),
    fbi_report('EFTA00020506', highlight_quote='chauffeur also told Epstein "I have something on you remember what I buried!"'),
    fbi_report('EFTA02729877', '"MCC Corruption Case" is about guards on duty when Epstein died', is_interesting=True),
    fbi_report('EFTA00161465', 'evidence inventory including a "List of Absent Items"', is_interesting=True),
    # FBI tips
    fbi_tip(
        'EFTA01660676',
        "about recently convicted rapists Tal and Oren Alexander at Epstein's house",
        show_full_panel=True,
        url='https://www.bbc.com/news/articles/c6271ngl014o',
    ),
    fbi_tip('EFTA01249591', f"about {HENRY_JARECKI}", show_full_panel=True),
    fbi_tip('EFTA00108851', f"from {STEVEN_HOFFENBERG} re: Epstein and the murder of Arthur Shapiro", is_interesting=True, truncate_to=(1_700, 2_600)),
    fbi_tip('EFTA00020490', 'from woman who thinks she encountered Epstein as a young girl'),
    fbi_tip('EFTA00090314', f'about {MASHA_DROKOVA}, Jared Kushner, Ivanka Trump, Chabad, {ALAN_DERSHOWITZ}, etc.', is_interesting=True),
    fbi_tip(
        'EFTA01683874',
        'from Confidential Human Source about "Epstein\'s personal hacker"',
        date='2017-11-27',
        is_interesting=10,
        truncate_to=(853, 4_200),
    ),
    # FinCEN
    fincen_sar('EFTA01656415', 'Charles Schwab', RICHARD_KAHN, "$45 million transaction"),
    fincen_sar('EFTA01656409', DEUTSCHE_BANK, DARREN_INDYKE, 'structured transactions'),
    grand_jury(
        'EFTA00222943',
        note='FBI agent testimony',
        highlight_quote="I believe that certain items were purposely removed from Mr. Epstein's home in anticipation of an execution of a search warrant",
        truncate_to=AUTO,
    ),
    grand_jury('EFTA00016349', note='charge list', date='2008-02-01', date_uncertain='before the arrest?'),
    DocCfg(id='EFTA00084614', author=PALM_BEACH_POLICE, note='incident report detailing the investigation into Jeffrey Epstein'),
    DocCfg(id='EFTA00007893', author=PALM_BEACH_POLICE, note=f"receipts, notes, bank statements of {GHISLAINE_MAXWELL}"),
    DocCfg(id='EFTA00005569', author=PALM_BEACH_POLICE, display_text='photo lineup featuring Epstein', date='2005-03-17'),
    DocCfg(id='EFTA00003868', author=PALM_BEACH_POLICE, display_text='photo lineup featuring Epstein', date='2006-08-09'),
    DocCfg(id='EFTA00128379', note='analysis of two of Epstein\'s desktop computers', date='2020-01-08', is_interesting=True),
    DocCfg(id='EFTA02730274', note='evidence inventory that appears to have since been deleted from the DOJ website'),
    DocCfg(id='EFTA00263284', note='notes about deceit and sexual manipulation by Australian professor Vincent Bulone', is_interesting=True),
    DocCfg(id='EFTA00001884', note='photo of letter from Virgin Islands DOJ to Epstein', date='2019-03-14'),
    DocCfg(id='EFTA00007157', note='victim list and police log'),
    DocCfg(id='EFTA01649103', date='2025-03-17T22:33:37', note='"MCC Corruption Case" is about guards on duty when Epstein died'),
    DocCfg(id='EFTA00029805', author=DOJ, note='policy doc', is_interesting=False),
    letter('EFTA01653121', FBI, ['USCIS'], "regarding an individual's cooperation in the investigation of Epstein and Maxwell"),
    letter('EFTA00098456', PAUL_G_CASSELL, ['Scotland Yard'], 'International Sex Trafficking by Jeffrey Epstein, contains court filings'),
    letter(
        'EFTA00016124',
        SDNY,
        [CHRISTIAN_EVERDELL, LAURA_A_MENNINGER, BOBBI_C_STERNHEIM],
        "re: unsearched Epstein computer backups that are no inaccessible",
        '2019-04-09',
        highlight_quote='the Government cannot permit you to review the contents of the Discs',
        truncate_to=(2_900, 3_900),
    ),

    # Emails
    EmailCfg(
        id='EFTA00129096',
        date='2025-04-03 7:13:35 PM',
        note=f'background check on Tim Draper and {MASHA_DROKOVA}',
        show_full_panel=True,
        truncate_to=NO_TRUNCATE,  # TODO this shouldn't be necessary?
    ),
    EmailCfg(id='EFTA00039878', author=BUREAU_OF_PRISONS, author_uncertain=True, recipients=[BUREAU_OF_PRISONS]),
    EmailCfg(id='EFTA00037692', author=BUREAU_OF_PRISONS, author_uncertain=True, recipients=[BUREAU_OF_PRISONS], recipient_uncertain=True),
    EmailCfg(id='EFTA00019994', author=BUREAU_OF_PRISONS, author_uncertain=True, recipients=[BUREAU_OF_PRISONS], recipient_uncertain=True),
    EmailCfg(id='EFTA00018398', author=BUREAU_OF_PRISONS, author_uncertain=True, recipients=[USANYS], recipient_uncertain=True),
    EmailCfg(id='EFTA00037551', author=BUREAU_OF_PRISONS, recipients=[BUREAU_OF_PRISONS], recipient_uncertain=True),
    EmailCfg(id='EFTA00039357', author=BUREAU_OF_PRISONS, recipients=['DOJ Inspector General']),
    EmailCfg(id='EFTA00036630', author=BUREAU_OF_PRISONS, recipients=[BUREAU_OF_PRISONS], note='about cameras'),
    EmailCfg(id='EFTA00019169', author=FBI, author_uncertain=True, recipients=[USANYS], recipient_uncertain=True),
    EmailCfg(id='EFTA02730483', author=FBI, date='2023-07-11T08:25:00', date_uncertain='actually reply timestamp'),
    EmailCfg(id='EFTA02731552', author=FBI, recipients=[USANYS], recipient_uncertain=True, date='2021-05-26 16:12:00'),
    EmailCfg(id='EFTA00039971', author=FBI, recipients=[USANYS], recipient_uncertain=True),
    EmailCfg(id='EFTA00163507', author=FBI, note="quotes from Epstein's cellmate", is_interesting=True),
    EmailCfg(id='EFTA01649194', highlight_quote='Attached please find an updated list of the discrepancies'),
    DocCfg(id='EFTA01649074', attached_to_email_id='EFTA01649194'),
    EmailCfg(id='EFTA00037683', note=f"tip that the murder of DC Madam Jeanne Palfrey might be connected to Epstein's network"),
    EmailCfg(
        id='EFTA00215004',
        author='Alex Acosta',
        highlight_quote='Please do whatever you can to keep this from becoming public',
        note=f"Epstein's lawyer asks Acosta to (illegally) keep the non-prosecution agreement a secret",
        recipients=['USAFLS'],
    ),
    EmailCfg(
        id='EFTA00214992',
        highlight_quote='marching orders regarding what they can tell the girls',
        note=f"not informing victims is a violation of {CVRA}",
    ),
    fbi_evidence_review('EFTA01657122'),
    fbi_evidence_review('EFTA01657117'),
    fbi_evidence_review('EFTA01657113'),
    fbi_evidence_review('EFTA01657121'),
    fbi_evidence_review('EFTA01657111'),
    fbi_evidence_review('EFTA01657107'),
    fbi_evidence_review('EFTA01657097'),
    fbi_evidence_review('EFTA01657119'),
    fbi_evidence_review('EFTA01657124'),
    fbi_internal(
        'EFTA00172840',
        note=f'FBI investigation of {DAVID_COPPERFIELD} for rape of a young female closed by prosecutors',
        highlight_quote=f'weak and intimidated by the financial resources of Copperfield',
    ),
    fbi_internal(
        'EFTA01657299',
        highlight_quote='Brunel uses MC2 as a legitimate transport agency of underage girls into America for purposes of sex',
        note=f'interview of {JEAN_LUC_BRUNEL} partner Sergio Cordero',
        truncate_to=(10_240, 14_500),
    ),
    fbi_internal('EFTA01648955'),
    fbi_internal('EFTA00037690', highlight_quote='seems to be a conduit for money paid to female victims', note=BUTTERFLY_TRUST),

    # DOJ / USANYS emails
    EmailCfg(id='EFTA00039967', author='DOJ London', recipients=[USANYS]),
    EmailCfg(
        id='EFTA00039660',
        author='DOJ Chief Psychologist',
        note="report on Epstein's psychological state in jail",
        is_interesting=5,
        recipients=[USANYS],
    ),
    EmailCfg(id='EFTA00040145', date='2021-11-09 17:24:30', is_interesting=False),
    EmailCfg(
        id='EFTA00277089',
        author=USANYS,
        duplicate_ids=['EFTA00151184'],
        note="tip for the FBI / DOJ that Swedish billionaire Johan Eliasch may be connected to Epstein's crimes",
        recipients=[USANYS],
    ),
    EmailCfg(
        id='EFTA00157083',
        author=USANYS,
        highlight_quote='In his keychain he had the following passwords',
        note='list of passwords commonly used by Epstein',
        truncate_to=(1_054, 6_400),
    ),
    EmailCfg(id='EFTA00039796', author=SDNY, recipients=[USANYS]),
    fbi_internal('EFTA00021353'),

    # USANYS
    EmailCfg(
        id='EFTA00039989',
        note=f"ICE has an immigration hold on a man who might have important info about the Epstein case",
        is_interesting=4,
    ),
    usanys_internal_email('EFTA02731615'),
    usanys_internal_email('EFTA00030842'),
    usanys_internal_email('EFTA02731684'),
    usanys_internal_email('EFTA02731485'),
    usanys_internal_email('EFTA02731736'),
    usanys_internal_email('EFTA02731478'),
    usanys_internal_email('EFTA00039872'),
    usanys_internal_email('EFTA00039868'),
    usanys_internal_email('EFTA02731490'),
    usanys_internal_email('EFTA02731477'),
    usanys_internal_email('EFTA02731660'),
    usanys_internal_email('EFTA00039820'),
    usanys_internal_email('EFTA02731638'),
    usanys_internal_email('EFTA02731636'),
    usanys_internal_email('EFTA02731637'),
    usanys_internal_email('EFTA02731659'),
    usanys_internal_email('EFTA02731781'),
    usanys_internal_email('EFTA02731774'),
    usanys_internal_email('EFTA02731724'),
    usanys_internal_email('EFTA02731771'),
    usanys_internal_email('EFTA02731486'),
    usanys_internal_email('EFTA02731604'),
    usanys_internal_email('EFTA02731618'),
    usanys_internal_email('EFTA02731608'),
    usanys_internal_email('EFTA02731612'),
    usanys_internal_email('EFTA02731729'),
    usanys_internal_email('EFTA02731484'),
    usanys_internal_email('EFTA02731757'),
    usanys_internal_email('EFTA02731623'),
    usanys_internal_email('EFTA00089649', note=f"128,175 email attachments permanently lost", is_interesting=True),
    usanys_internal_email('EFTA00013640', note='list of devices', truncate_to=(600, 1_700)),
    usanys_internal_email('EFTA02731488', note=f"possible evidence of girls being trafficked to {LEON_BLACK}", is_interesting=10),
    usanys_internal_email('EFTA02731655', note=f"specific allegations against {LEON_BLACK}", is_interesting=10),
    usanys_internal_email('EFTA02731689', date='2023-06-09 20:14:00', truncate_to=SHORT_TRUNCATE_TO),
    usanys_internal_email('EFTA02731733', date='2021-05-17 17:29:00'),
    usanys_internal_email('EFTA02731754', date='2024-03-06T23:24:00'),
    usanys_internal_email('EFTA02731732', date='2024-03-06T12:21:00'),
    usanys_internal_email('EFTA02731528', date='2021-05-06 09:39:15'),
    usanys_internal_email('EFTA02731475', date='2023-05-31T20:53:00'),
    usanys_internal_email('EFTA02731697', date='2021-06-07 17:33:00'),
    usanys_internal_email('EFTA02731583', date='2022-01-21 17:28:00'),
    usanys_internal_email('EFTA02731587', date='2022-01-21 17:28:00'),
    EmailCfg(
        id='EFTA02731737',
        author=USANYS,
        author_uncertain=True,
        date='2023-06-30T16:05:00',
        is_interesting=10,
        recipients=[FBI],
        truncate_to=5000,
    ),
    EmailCfg(
        id='EFTA00090614',
        author=USANYS,
        author_uncertain=True,
        note='alleges cover up of crimes of wealthy / powerful people by DA Cyrus Vance',
        recipients=[FBI],
        recipient_uncertain=True,
        truncate_to=7000,
    ),
    EmailCfg(id='EFTA00029435', author=USANYS),
    EmailCfg(id='EFTA02731755', author=USANYS),
    EmailCfg(id='EFTA00039662', author=USANYS),
    EmailCfg(id='EFTA00040141', author=USANYS),
    EmailCfg(id='EFTA02731644', author=USANYS),
    EmailCfg(id='EFTA00040144', author=USANYS),
    EmailCfg(id='EFTA00039813', author=USANYS),
    EmailCfg(id='EFTA00039995', author=USANYS, is_interesting=False),
    EmailCfg(id='EFTA00039890', author=USANYS, is_interesting=False),
    EmailCfg(id='EFTA00039815', author=USANYS, is_interesting=False),
    EmailCfg(id='EFTA00039825', author=USANYS, is_interesting=False),
    EmailCfg(id='EFTA02731783', author=USANYS, date='2022-01-21 17:28:00'),
    EmailCfg(id='EFTA02731578', author=USANYS, date='2021-05-28 10:00:00'),
    EmailCfg(id='EFTA00039983', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA00039886', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA02731651', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA02731775', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA02731646', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA02731640', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA02731643', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA02731501', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA02731633', author=USANYS, author_uncertain=True),
    EmailCfg(id='EFTA01660679', author=USANYS, author_uncertain=True, recipients=[FBI], recipient_uncertain=True),
    EmailCfg(id='EFTA02731699', author=USANYS, author_uncertain=True, recipients=[FBI], date='2021-05-27 10:19:00'),
    EmailCfg(id='EFTA02730468', author=USANYS, recipients=[USANYS], date='2019-07-11T08:25:00', date_uncertain='just wrong'),
    EmailCfg(id='EFTA00019925', author=USANYS, recipients=[USANYS], note="death of Epstein's cellmate Efrain Reyes"),
    EmailCfg(id='EFTA00040121', author=USANYS, recipients=[ATT_COURT_APPEARANCE_TEAM]),
    EmailCfg(id='EFTA02731630', author=USANYS, recipients=[FBI]),
    EmailCfg(id='EFTA00014718', author=USANYS, recipients=['Daily Beast']),
    EmailCfg(id='EFTA02731593', author=USANYS, recipients=['Manhattan DA']),
    EmailCfg(id='EFTA00039419', author=USANYS, recipients=['Manhattan DA']),
    EmailCfg(id='EFTA02731617', author=USANYS, recipients=[SDNY], date='2021-04-28T15:05:41'),
    EmailCfg(id='EFTA00151184', author=USANYS, recipients=[USANYS]),
    EmailCfg(id='EFTA00014767', author=USANYS, recipients=[USANYS], author_uncertain=True, is_interesting=False),
    EmailCfg(id='EFTA00015851', author=USANYS, recipients=[USANYS], author_uncertain=True, is_interesting=False),
    EmailCfg(id='EFTA00039879', author=USANYS, recipients=[USANYS], recipient_uncertain=True),
    EmailCfg(id='EFTA02731632', recipients=[OFFICE_OF_THE_DEPUTY_ATTORNEY_GENERAL]),
    EmailCfg(id='EFTA02731721', recipients=[USANYS]),
    EmailCfg(id='EFTA02731582', recipients=[USANYS]),
    EmailCfg(id='EFTA00039884', recipients=[USANYS]),
    EmailCfg(id='EFTA02731512', recipients=[USANYS], note=f'specific allegations against {GHISLAINE_MAXWELL}'),
    EmailCfg(id='EFTA02731514', recipients=[USANYS], comment='journal upload followup'),
    EmailCfg(id='EFTA02731511', recipients=[USANYS], comment='journal upload followup'),
    EmailCfg(id='EFTA02731515', recipients=[USANYS], comment='journal upload followup'),
    EmailCfg(id='EFTA02731735', recipients=[USANYS], recipient_uncertain=True, date='2024-03-04T05:04:00'),
    EmailCfg(id='EFTA02731480', recipients=[USANYS], recipient_uncertain=True),
    EmailCfg(id='EFTA02731482', recipients=[USANYS], recipient_uncertain=True),
    EmailCfg(id='EFTA02731713', recipients=[USANYS], recipient_uncertain=True),
    EmailCfg(id='EFTA02731718', recipients=[USANYS], recipient_uncertain=True),
    EmailCfg(id='EFTA02731715', recipients=[USANYS], duplicate_ids=['EFTA02731762']),
]
