# Rich reference: https://rich.readthedocs.io/en/latest/reference.html
import json
from copy import deepcopy
from datetime import datetime
from os import devnull
from pathlib import Path
from typing import Mapping, Sequence

from rich import box
from rich.align import Align
from rich.console import Console, Group, RenderableType
from rich.markup import escape
from rich.panel import Panel
from rich.padding import Padding
from rich.table import Table
from rich.text import Text
from rich.theme import Theme

from epstein_files.output.demi_table import build_demi_table
from epstein_files.output.epstein_highlighter import EpsteinHighlighter
from epstein_files.output.highlight_config import HIGHLIGHT_GROUPS
from epstein_files.output.rich import *
from epstein_files.util.constant.html import CONSOLE_HTML_FORMAT, HTML_TERMINAL_THEME, PAGE_TITLE
from epstein_files.util.constant.names import UNKNOWN
from epstein_files.util.constant.output_files import GH_PROJECT_URL, SITE_DESCRIPTIONS, parenthesize
from epstein_files.util.constant.strings import *
from epstein_files.util.constant.urls import *
from epstein_files.util.constants import HEADER_ABBREVIATIONS
from epstein_files.util.env import args
from epstein_files.util.helpers.data_helpers import json_safe, sort_dict, without_falsey
from epstein_files.util.helpers.file_helper import log_file_write
from epstein_files.util.helpers.link_helper import link_markup, link_text_obj
from epstein_files.util.helpers.string_helper import quote
from epstein_files.util.logging import logger

TITLE_WIDTH = 50
SUBTITLE_WIDTH = 110
NUM_COLOR_KEY_COLS = 6
NA_TXT = Text(NA, style='dim')
SKIPPED_FILE_MSG_PADDING = (0, 0, 0, 4)
SUBTITLE_PADDING = (2, 0, 1, 0)
GREY_NUMBERS = [58, 39, 39, 35, 30, 27, 23, 23, 19, 19, 15, 15, 15]
VALID_GREYS = [0, 3, 7, 11, 15, 19, 23, 27, 30, 35, 37, 39, 42, 46, 50, 53, 54, 58, 62, 63, 66, 69, 70, 74, 78, 82, 84, 85, 89, 93]

DOJ_PAGE_LINK_MSG = 'WIP page with documents from the Epstein Files Transparency Act'
SITE_GLOSSARY_MSG = f"These pages include the following views of the underlying collection of Epstein's files:"
YOU_ARE_HERE = Text('«').append('you are here', style='bold khaki1 blink').append('»')

DATASET_DESCRIPTION_STYLE = 'gray74'
INFO_STYLE = 'white dim italic'
KEY_STYLE = 'dim'
KEY_STYLE_ALT = 'light_steel_blue3'
LAST_TIMESTAMP_STYLE = 'wheat4'
OTHER_PAGE_MSG_STYLE = 'gray78 dim'
PATH_STYLE = 'deep_pink3'
STR_VAL_STYLE = 'cornsilk1 italic'
STR_VAL_STYLE_ALT = 'light_yellow3 italic'
SECTION_HEADER_STYLE = 'bold white on blue3'
SOCIAL_MEDIA_LINK_STYLE = 'pale_turquoise4'
SUBSTACK_POST_LINK_STYLE = 'bright_cyan'
SYMBOL_STYLE = 'grey70'
TABLE_BORDER_STYLE = 'grey46'
TABLE_TITLE_STYLE = f"gray54 italic"
TITLE_STYLE = 'black on bright_white bold'

OTHER_SITE_LINK_STYLE = 'dark_goldenrod'


def print_color_key() -> None:
    color_table = build_table('Rough Guide to Highlighted Colors', show_header=False)
    num_colors = len(HIGHLIGHTED_GROUP_COLOR_KEYS)
    row_number = 0

    for i in range(0, NUM_COLOR_KEY_COLS):
        color_table.add_column(f"color_col_{i}", justify='center')

    while (row_number * NUM_COLOR_KEY_COLS) < num_colors:
        idx = row_number * NUM_COLOR_KEY_COLS
        color_table.add_row(*HIGHLIGHTED_GROUP_COLOR_KEYS[idx:(idx + NUM_COLOR_KEY_COLS)])
        row_number += 1

    print_centered(vertically_pad(color_table))


def print_other_page_link(epstein_files: 'EpsteinFiles') -> None:
    if args._site_type == SiteType.CURATED:
        txt = THE_OTHER_PAGE_TXT + Text(f' is uncurated and has all {len(epstein_files.emails):,} emails')
        txt.append(f" and {len(epstein_files.other_files):,} unclassifiable files")
    else:
        txt = THE_OTHER_PAGE_TXT + (f' displays a curated collection of emails and')
        txt.append(" unclassifiable files of particular interest")

    print_centered(parenthesize(txt), style=OTHER_PAGE_MSG_STYLE)
    chrono_emails_link = link_text_obj(SiteType.get_url(SiteType.CHRONOLOGICAL_EMAILS), 'a page', style='light_slate_grey bold')
    chrono_emails_txt = Text(f"there's also ").append(chrono_emails_link)
    chrono_emails_txt.append(' with all the emails in chronological order')
    print_centered(parenthesize(chrono_emails_txt), style=OTHER_PAGE_MSG_STYLE)


def print_page_title(expand: bool = True, width: int | None = None) -> None:
    warning = f"This page was generated by {link_markup('https://pypi.org/project/rich/', 'rich')}."
    print_centered(f"{warning} It is not optimized for mobile.", style='dim')
    title_panel = Panel(Text('The Epstein Files', justify='center'), expand=expand, style=TITLE_STYLE, width=width)
    print_centered(vertically_pad(title_panel))
    _print_social_media_links()
    console.line()


def print_section_links() -> None:
    """Print links to the various sections within the curated page."""
    for table_piece in build_demi_table(SECTION_LINK_MSG, SECTION_LINKS):
        print_centered(table_piece)


def print_section_header(msg: str, style: str = SECTION_HEADER_STYLE, is_centered: bool = False) -> None:
    panel = Panel(Text(msg, justify='center'), expand=True, padding=(1, 1), style=style)
    panel = Align.center(panel) if is_centered else panel
    console.print(Padding(panel, (3, 5, 1, 5)))


def print_section_summary_table(table: Table) -> None:
    """Precede it with internal section links if it's the curated page."""
    if args._site_type == SiteType.CURATED:
        console.line()
        print_section_links()

    print_centered(Padding(table, (2, 0, 2, 0)))


def print_title_page_header() -> None:
    """Top half of the title page."""
    links = {site_type: SiteType.link_txt(site_type) for site_type in SITE_DESCRIPTIONS.keys()}

    def site_link_line(site_type: SiteType, bulleted_link: Text) -> Text:
        you_are_here = YOU_ARE_HERE if site_type == args._site_type else ''
        return Text('➱ ').append(bulleted_link).append(' ').append(you_are_here)

    # Print the stuff
    print_page_title(width=TITLE_WIDTH)
    sites_txt = Text('').append(SITE_GLOSSARY_MSG, style='wheat4 bold').append('\n\n')
    links_txts = [site_link_line(site_type, link) for site_type, link in links.items()]
    max_link_len = max(len(link.plain) for link in links.values())
    num_link_indent_spaces = max(2, int((len(SITE_GLOSSARY_MSG) - max_link_len) / 2)) - 2
    sites_txt.append(indent_txt(join_texts(links_txts, '\n'), num_link_indent_spaces))
    print_centered(Panel(sites_txt, border_style='dim', padding=(1, 5)))
    console.line()
    print_starred_header('Not All Epstein Files Are Here!', num_spaces=9 if args.all_emails else 6, num_stars=14)
    print_centered(f"This dataset includes everything from the {HOUSE_OVERSIGHT_TRANCHE}", style=DATASET_DESCRIPTION_STYLE)
    print_centered(f"as well as a curated selection of the {DOJ_2026_TRANCHE}.\n", style=DATASET_DESCRIPTION_STYLE)

    if args._site_type == SiteType.CURATED:
        print_section_links()


def print_title_page_tables(epstein_files: 'EpsteinFiles') -> None:
    """Bottom half of the title page."""
    console.line()
    _print_abbreviations_table()
    print_centered(epstein_files.overview_table())
    _print_external_links()
    console.line()
    print_color_key()
    print_centered(f"(if you think there's an attribution error or can deanonymize an {UNKNOWN} contact {CRYPTADAMUS_TWITTER})", 'grey46')
    print_centered(parenthesize('note this site is based on the government provided OCR text which is not always the greatest'), 'grey23')
    print_centered(f"(thanks to {link_markup('https://x.com/ImDrinknWyn', '@ImDrinknWyn', 'dodger_blue3')} + others for help attributing redacted emails)")
    print_centered_link(SiteType.get_url(SiteType.JSON_METADATA), "(explanations of author attributions)", style='magenta')


def _link_with_comment(url: str, comment: str | Text, _link_text: str = '') -> Text:
    link_text = _link_text if _link_text else (JMAIL if url == JMAIL_URL else None)

    if isinstance(comment, Text):
        comment = comment
        link_style = 'navajo_white3 bold'
    else:
        comment = enclose(Text(comment, 'color(195) dim italic'), '()', 'gray27')
        link_style = EXTERNAL_STYLE

    return link_text_obj(url, link_text=link_text, style=link_style).append(' ').append(comment)


def _print_abbreviations_table() -> None:
    table = build_table(title="Abbreviations Used Frequently In These Conversations", show_header=False)
    table.add_column("Abbreviation", justify="center", style='bold')
    table.add_column("Translation", justify="center", min_width=62, style="white")

    for k, v in HEADER_ABBREVIATIONS.items():
        table.add_row(highlighter(k), v)

    console.print(Align.center(vertically_pad(table)))


def _print_external_links() -> None:
    console.line()
    print_centered(Text('External Links', style=TABLE_TITLE_STYLE))
    doj_search_link = join_texts([link_text_obj(DOJ_SEARCH_URL, 'search', style=ARCHIVE_ALT_LINK_STYLE)], encloser='()')
    print_centered(_link_with_comment(DOJ_2026_URL, doj_search_link, 'Dept of Justice Epstein Files Transparency Act Disclosures'))
    raw_docs_link = link_text_obj(OVERSIGHT_DRIVE_URL, 'raw files', style=ARCHIVE_ALT_LINK_STYLE)
    raw_docs_link = join_texts([raw_docs_link], encloser='()')
    print_centered(_link_with_comment(OVERSIGHT_REPUBS_PRESSER_URL, raw_docs_link, 'Official Oversight Committee Press Release'))

    for url, link in EXTERNAL_LINK_MSGS.items():
        print_centered(_link_with_comment(url, link))


def _print_social_media_links() -> None:
    print_centered_link(
        SUBSTACK_URL,
        "I Made Epstein's Text Messages Great Again (And You Should Read Them)",
        style=f'{SUBSTACK_POST_LINK_STYLE} bold'
    )

    print_centered_link(SUBSTACK_URL, SUBSTACK_URL.removeprefix('https://'), style=f'{SUBSTACK_POST_LINK_STYLE} dim')

    social_links = [
        link_text_obj('https://universeodon.com/@cryptadamist/115572634993386057', '@mastodon', style=SOCIAL_MEDIA_LINK_STYLE),
        link_text_obj(SUBSTACK_URL, '@substack', style=SOCIAL_MEDIA_LINK_STYLE),
        link_text_obj('https://x.com/Cryptadamist/status/1990866804630036988', '@twitter', style=SOCIAL_MEDIA_LINK_STYLE),
        link_text_obj(GH_PROJECT_URL, '@github', style=SOCIAL_MEDIA_LINK_STYLE)
    ]

    print_centered(join_texts(social_links, join='  /  '))#, encloser='()'))#, encloser='‹›'))
