"""
Mobile vs. non-mobile.
"""
from dataclasses import dataclass
from datetime import datetime
from typing import ClassVar

from epstein_files.util.helpers.link_helper import link_markup
from epstein_files.util.helpers.string_helper import iso_timestamp

ALL_OTHER_FILES_MULTIPLIER = 1.5  # applied when --all-other-files is in use
DEFAULT_WIDTH = 155

RICH_LINK_MARKUP = link_markup('https://pypi.org/project/rich/', 'rich')
MOBILE_WARNING = f"This page was generated by {RICH_LINK_MARKUP}. It is not optimized for mobile."


@dataclass
class SiteConfig:
    abbreviations_width: ClassVar[int | None] = 62
    num_color_key_cols: ClassVar[int] = 6
    other_files_preview_chars: ClassVar[int] = 900
    show_emailer_tables: bool = True
    width: ClassVar[int] = DEFAULT_WIDTH

    @classmethod
    def format_text_msg_time(cls, dt: datetime) -> str:
        return iso_timestamp(dt)


class MobileConfig(SiteConfig):
    abbreviations_width: ClassVar[int | None] = None
    num_color_key_cols: ClassVar[int] = 6
    other_files_preview_chars: ClassVar[int] = 300
    show_emailer_tables: bool = False
    width: ClassVar[int] = 45

    @classmethod
    def format_text_msg_time(cls, dt: datetime) -> str:
        return dt.strftime(r"%-d/%-m/%-y %-H:%M")
