"""
Site directory panel.
"""
from dataclasses import dataclass, field
from pathlib import Path
from typing import Self

from rich.console import Group, NewLine
from rich.markup import escape
from rich.padding import Padding
from rich.panel import Panel
from rich.text import Text

# from epstein_files.output.html.elements import div_class, div_tag, build_html_list
from epstein_files.output.html.positioned_rich import CENTERED
from epstein_files.util.constant.strings import (AUX_SITE_LINK_STYLE, CHRONOLOGICAL, DOJ_2026_TRANCHE,
     EPSTEIN_FILES_NOV_2025, HOUSE_OVERSIGHT_TRANCHE)
from epstein_files.util.external_link import ExternalLink
from epstein_files.util.helpers.rich_helpers import bold, join_texts
from epstein_files.util.logging import logger

DIRECTORY_STYLE = 'wheat4'
SITE_GLOSSARY_MSG = f"The following views of the underlying selection of Epstein Files are available:"
YOU_ARE_HERE = Text('«').append('you are here', style='bold khaki1 blink').append('»')
TITLE = Text('').append(SITE_GLOSSARY_MSG, style=f'{DIRECTORY_STYLE} bold')


@dataclass
class SiteDirectory:
    primary_links: dict[str, ExternalLink] = field(default_factory=dict)
    secondary_links: list[ExternalLink] = field(default_factory=list)  # TODO: unused
    category_links: list[ExternalLink] = field(default_factory=list)

    @property
    def all_links(self) -> list[ExternalLink]:
        return [link for link in self.primary_links.values()] + self.secondary_links + self.category_links

    @property
    def link_directory(self) -> dict[str, ExternalLink]:
        """Everything but mobile."""
        return {
            **self.primary_links,
            **{cl.link_text: cl for cl in self.category_links}
        }

    def to_html(self) -> str:
        from epstein_files.output.layout_elements.list_panel import ListPanel
        from epstein_files.util.env import args, site_config

        link_txts = [
            link.__rich__().append(Text(' ').append(YOU_ARE_HERE) if site == args._site else '')
            for site, link in self.link_directory.items()
        ]

        list_panel = ListPanel(
            border_style='gray15 dim',
            list_css_class='site_directory',
            padding=site_config.directory_padding,
            text=link_txts,
            title=TITLE,
        )

        css_props = {
            **CENTERED,
        }

        return list_panel.to_div(css=css_props)

    def __rich__(self) -> Padding:
        """Panel with links to the various sites generated by this code."""
        from epstein_files.util.env import args, site_config
        base_width = len(SITE_GLOSSARY_MSG)

        links_txts = [
            _bulleted_site_link(site, link.__rich__())
            for site, link in self.link_directory.items()
        ]

        if args.mobile:
            num_link_indent_spaces = 0
        else:
            max_link_len = max(len(link.plain) for link in links_txts)
            num_link_indent_spaces = max(2, int((base_width - max_link_len) / 2)) - 2

        site_links_list_txt = join_texts(links_txts, '\n')

        panel_contents = [
            TITLE,
            Padding(site_links_list_txt, (1, 0, 0, num_link_indent_spaces)),
        ]

        if args.mobile:
            panel_contents.append(Text("\nNot all views are available on mobile.", DIRECTORY_STYLE))

        panel = Panel(
            Group(*panel_contents),
            border_style='grey23',
            expand=False,
            padding=(1, site_config.site_glossary_horizontal_padding),
            width=min(
                base_width + (2 * site_config.site_glossary_horizontal_padding) + 2,
                args.width or site_config.site_glossary_horizontal_padding,
            ),
        )

        return Padding(panel, (1, 0))


# def _bulleted_site_link(site: Site, link: Text) -> Text:
def _bulleted_site_link(site: str, link: Text) -> Text:
    """These go in the site directory panel."""
    from epstein_files.output.site.sites import Site
    from epstein_files.util.env import args
    you_are_here = ''

    if args.mobile:
        if site == Site.CHRONOLOGICAL_MOBILE and args.output_chrono:
            you_are_here = YOU_ARE_HERE
        elif site == Site.CURATED:
            you_are_here = YOU_ARE_HERE

        if args._site not in Site.mobile_compatible_types():
            link.stylize('dim strike')
    elif site == args._site:
        you_are_here = YOU_ARE_HERE

    return Text('➱ ').append(link).append(' ').append(you_are_here)
